[profile.default]
src = "src"
out = "test/build"
cache = true
cache_path = "test/cache"
libs = ["lib"]
allow_paths=[".code"]

remappings = [
    "@harness/=../../_testHarness/",
    "test/KromaPortal/:@code/=.code/KromaPortal/implementation/",
    "test/Colosseum/:@code/=.code/Colosseum/implementation/",
    "script/:@code/=.code/Colosseum/implementation/",
    ".code/KromaPortal:@openzeppelin/=.code/KromaPortal/implementation/node_modules/@openzeppelin/",
    ".code/KromaPortal:@rari-capital/=.code/KromaPortal/implementation/node_modules/@rari-capital/",
    ".code/Colosseum:@openzeppelin/=.code/Colosseum/implementation/node_modules/@openzeppelin/",
    ".code/Colosseum:@rari-capital/=.code/Colosseum/implementation/node_modules/@rari-capital/"
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
