/**
 * The handler reference the model reads, condensed from the researcher
 * README to the seven handler types researchers use for nearly every
 * generic field, and the `edit` and `where` forms they write.
 *
 * It states V1's run-time behaviour rather than the README's prose where
 * the two differ in ways a draft trips over: how a bare method name is
 * resolved, that `add` replays logs into a set keyed by `select`, that log
 * values are chain-prefixed before `where` compares them, that role names
 * come from the ABI and not from the getters' values. Every example is a
 * handler from a committed template, so nothing here teaches a form V1
 * would not run.
 *
 * A string constant rather than a markdown file: the package ships the
 * `tsc` output, which would leave a `.md` file behind.
 */
import { PROBE_RANGE } from '../facts'

export const HANDLER_DOCS = [
  'Every field has exactly one `handler` of one of the seven types below, with only the keys listed for that type; any other key is an error. Values are described as they appear in the discovered output, the way the baseline in section 4 shows them (addresses chain-prefixed, e.g. `eth:0x…`).',
  '',
  '### References',
  '',
  'A string that is exactly `{{ name }}` stands for the value of another field. References are accepted in `args` and `address` (call), `length` and `indices` (array), `slot` and `offset` (storage), and nowhere else.',
  '',
  '- `name` is a baseline field, another field you add, or a field of the existing template that has a `handler`; a field with only `copy` gets its value after every handler has run, so it cannot be referenced. `{{ $.address }}` is this contract’s own address, chain-prefixed (`eth:0x…`), which the ABI encoder does not take: in `args`, write the address as a plain `0x…` literal instead.',
  '- Proxy values (`$admin`, `$implementation`, `$pastUpgrades`, …) are not referenceable.',
  '- `{{ name.key }}` reaches into an object value, e.g. `{{ constructorArgs._owner }}` of a `constructorArgs` field with `nameArgs: true`. It cannot index into arrays, and the outputs of a function returning several values are positional, so it cannot reach into those either.',
  '- A reference resolves to the raw handler value: before `edit`, with addresses unprefixed, so it can be passed straight into `args`.',
  '- References must not form a cycle.',
  '',
  '### Relatives',
  '',
  'Discovery analyses every address a field holds next, as part of this system. `"ignoreRelative": true` on a `call`, `array`, `event`, `accessControl` or `storage` handler keeps the value but stops discovery from following its addresses; use it for fields that list instances (deployed tokens, created games or pools) rather than components.',
  '',
  '### call',
  '',
  'Calls one view function once. The field holds its return value; several named return values, or a struct, become an object keyed by name (as the baseline shows multi-value getters).',
  '',
  '- `method` (optional): either a bare function name, looked up in this contract’s ABI by name and by the number of `args`, or a full human-readable fragment such as `function getAddress(bytes32 key) view returns (address)`. When omitted, the field name is the method name. A `name(types)` signature such as `isSequencer(address)` is not accepted.',
  '- `args` (required, `[]` for none): one entry per input, each a literal or a reference. Integers as JSON numbers (decimal strings above 2^53), booleans as `1` and `0` (`args` takes no JSON `true` or `false`, and the encoder reads any string, `"false"` included, as true), bytes as `0x` hex, addresses as plain `0x…` hex without the chain prefix: arguments reach the ABI encoder as written.',
  '- `address` (optional): call another contract, given as a reference to a field that holds its address (`"{{ registry }}"`). `method` must then be the full fragment, because the other contract’s ABI is not available.',
  '- `expectRevert` (optional): for a call that reverts today by design; the field then holds `"EXPECT_REVERT"`.',
  '- Several `call` fields may read the same function with different literal `args`, one field per key that is fixed in the source (the values of an enum, the ids of known quorums). Name each after the function and its key, the way `getOperatorSetParams(uint8)` is read for quorums 0, 1 and 2 as `operatorSetParamsQuorum1`, `operatorSetParamsQuorum2`, `operatorSetParamsQuorum3`.',
  '',
  'Examples. The Succinct entry of a verifier config keyed by an enum value that is fixed in the source; a getter of another contract whose address a field holds:',
  '',
  '```json',
  '{ "type": "call", "method": "getZkConfig", "args": [2] }',
  '{ "type": "call", "address": "{{ nodeSettings }}", "method": "function getUnstakingPeriod() view returns (uint256)", "args": [] }',
  '```',
  '',
  '### array',
  '',
  'Calls a view function that takes exactly one unsigned integer (`uint16`, `uint32`, `uint64` or `uint256`) once per index and holds the results as a JSON array, in index order.',
  '',
  '- `method` (optional): bare name or full fragment, as for `call`; omitted, the field name is used.',
  '- `length` (optional): a number or a reference to a field holding the length. Indices `startIndex` … `startIndex + length - 1` are read, and a revert is an error.',
  '- Without `length` and `indices`, the method is called from `startIndex` upwards until it reverts, at most `maxLength` times (default 100). Reading `maxLength` values is an error (also when `length` exceeds `maxLength`), so raise it for longer arrays.',
  '- `indices` (optional): the literal indices to read, e.g. `[0, 1, 2, 3]` for the values of an enum, or a reference to a field holding an array of indices. Not together with `length`.',
  '- `startIndex` (optional, default 0): the first index when enumerating.',
  '- A `uint8` key is not accepted, and the handler fails to construct. A getter keyed by a `uint8` is keyed by an enum in the source: read it with one `call` per enum value whose state matters (see `call`), or leave it out.',
  `- Discovery already reads every getter with one \`uint256\` argument at indices ${PROBE_RANGE} (marked "probed" in section 4). An \`array\` field named exactly like that getter replaces the probe with the full array.`,
  '',
  'Examples. Pools 1 … maxAssetId, with the length taken from a baseline getter; the holders of the four roles of an enum:',
  '',
  '```json',
  '{ "type": "array", "method": "stargateImpls", "startIndex": 1, "length": "{{ maxAssetId }}" }',
  '{ "type": "array", "method": "function roleHolders(uint256 role) view returns (address[])", "indices": [0, 1, 2, 3] }',
  '```',
  '',
  '### event',
  '',
  'Replays this contract’s logs of the named events from deployment to the discovered block, oldest first. Two forms; use exactly one.',
  '',
  '- `add` (with optional `remove`): logs matching an `add` action put their row into a set, logs matching a `remove` action take it out. The row is the `select`ed value, and rows are deduplicated by `dedupBy` when given, else by `select`. So `add` alone over an append-only event is the set of distinct selected values, in order of first appearance; `add` + `remove` is membership (an allowlist). A log that matches both an `add` and a `remove` action is an error. The field holds a JSON array.',
  '- `set`: keeps the latest matching log only; the field holds its selected value, not an array.',
  '- `select` (optional): one parameter name (the value is that parameter) or a list of names (the value is an object with those keys). Without it, the value is an object of all named parameters (just the value for a one-parameter event). A dotted path reaches into a struct parameter by position, because decoded structs are arrays: `config.1` is the second member of a `config` struct.',
  '- `groupBy` (optional): a parameter name. The field becomes an object keyed by that parameter’s value, with the `add`/`remove` or `set` logic applied per key; `set` + `groupBy` is "the latest value per key".',
  '- `dedupBy` (optional, `add` form only): the parameter(s) that make two rows the same, when that differs from `select`; the latest row per key is kept.',
  '- `flatten` (optional, `add` form only): with exactly one `select`ed parameter that is an array, one row per element.',
  '- An action is `{ "event": …, "where": … }`. `event` is a bare event name, a full fragment such as `event RevertBatch(uint256 indexed startBatchIndex, uint256 indexed finishBatchIndex)`, or a list of them. A bare name resolves to the first declaration of that name in the ABI listed in section 4; to read another overload, write its full fragment. Several events in one action must be compatible: every parameter of the event with the fewest parameters must appear, with the same name, type and indexed flag, in each other event of the action.',
  '- `select`, `groupBy`, `dedupBy` and every `#name` in `where` must be parameters of every event the field reads.',
  '- `where` (optional) filters the logs of the action. The forms researchers write are `["=", "#name", literal]` and `["!=", "#name", literal]`, where `#name` is a log parameter and the comparison is exact (`===`); other operators of the same small language exist and are documented in the discovery README. Log values are compared as: integers as JSON numbers (decimal strings above 2^53), booleans as booleans, bytes and bytes32 as lowercase `0x` hex, and addresses chain-prefixed and checksummed, because log values are chain-prefixed before the comparison. So an address literal is written like the addresses in the baseline, `["=", "#account", "eth:0x798576400F7D662961BA15C6b3F3d813447a26a6"]`; a bare `0x…` never matches.',
  '',
  'Examples. Distinct pooled tokens with their LP token, one row per `l1Token`; the latest owner of every token id:',
  '',
  '```json',
  '{ "type": "event", "select": ["l1Token", "lpToken"], "dedupBy": "l1Token", "add": { "event": "L1TokenEnabledForLiquidityProvision" } }',
  '{ "type": "event", "select": "to", "set": { "event": "Transfer" }, "groupBy": "tokenId" }',
  '```',
  '',
  '### accessControl',
  '',
  'The role table of an OpenZeppelin AccessControl contract, rebuilt from its `RoleGranted`, `RoleRevoked` and `RoleAdminChanged` logs (the standard OpenZeppelin signatures). The field must be named `accessControl`. It holds `{ "<role>": { "adminRole": "<role>", "members": ["eth:0x…", …] }, … }` for `DEFAULT_ADMIN_ROLE` and every role that appears in those logs.',
  '',
  '- Role names are automatic in two cases: the zero hash is `DEFAULT_ADMIN_ROLE`, and for every 0-argument function in the ABI whose name ends in `_ROLE` (e.g. `PROPOSER_ROLE()`) the hash `keccak256("PROPOSER_ROLE")` is named `PROPOSER_ROLE`. The getter’s value is not read for this. Every other role shows as its raw hash.',
  '- `roleNames` (optional): bytes32 hash → name, for roles the automatic naming misses: a `*_ROLE()` getter whose constant is not the keccak256 of its exact name (check the source, e.g. `keccak256("PROPOSER")` or a hex literal), with the getter’s baseline value as key and its name as value. Entries here win over automatic names.',
  '- `includeEmptyRoles` (optional): also list named roles that have no log yet.',
  '- Leave out `pickRoleMembers`: it turns the field into one role’s member list.',
  '',
  'Examples. The common case; a role whose hash is not the keccak256 of its getter name:',
  '',
  '```json',
  '{ "type": "accessControl" }',
  '{ "type": "accessControl", "roleNames": { "0x3f3b3bf06419b25db8f1ac3dfb014d79b6fb633e65d1ca540c6a3c665e32e106": "GOBLIN_ROLE" } }',
  '```',
  '',
  '### storage',
  '',
  'Reads one raw storage slot of this contract. Use it only for state that no getter or event exposes, and only when the source spells the slot out (a slot constant, or a variable whose position is unambiguous); never guess a layout.',
  '',
  '- `slot`: a number, a `0x` hex string, a decimal string, a reference, or a list of those. A list is a mapping path: `[5, key]` is the entry for `key` of the mapping at slot 5, `[5, key1, key2]` a nested mapping, `[4]` alone the start of the data of the dynamic array at slot 4.',
  '- `offset` (optional): added to the computed slot, for a struct member or an array element.',
  '- `returnType` (optional): `bytes` (default, the 32-byte word as hex), `address` (the low 20 bytes), `number`, or `uint8` (the lowest byte).',
  '',
  'Example. An address kept in slot 4 without a getter:',
  '',
  '```json',
  '{ "type": "storage", "slot": 4, "returnType": "address" }',
  '```',
  '',
  '### constructorArgs',
  '',
  'Decodes the constructor arguments of this address’s deployment with the constructor in the ABI, the one section 4 lists when it has parameters. The field must be named `constructorArgs`. For a proxy that is the proxy’s own constructor (logic, admin, init data), not the implementation’s, so use it for contracts without a proxy whose constructor sets state no getter exposes.',
  '',
  '- `nameArgs` (optional): `true` makes the value an object keyed by the constructor parameter names instead of a positional array, so other fields can reference `{{ constructorArgs.<name> }}`.',
  '',
  'Example:',
  '',
  '```json',
  '{ "type": "constructorArgs", "nameArgs": true }',
  '```',
  '',
  '### hardcoded',
  '',
  'A fixed value written into the template. Use it only for a constant in the source that no getter exposes (a `private` or `internal` constant), with the value exactly as the source defines it.',
  '',
  '- `value`: any JSON value.',
  '',
  'Example. A challenge period of 3 days (259200 seconds) that the source defines as a constant, shown as a duration with `"edit": ["format", "FormatSeconds"]`:',
  '',
  '```json',
  '{ "type": "hardcoded", "value": 259200 }',
  '```',
  '',
  '### edit',
  '',
  '`edit` (optional, next to `handler`) transforms the field’s value after all handlers ran. The two forms researchers write:',
  '',
  '- `["format", "FormatSeconds"]`: a number of seconds becomes a duration, `86400` → `"1d"`. For delays, periods and timeouts.',
  '- `["get", key, …]`: keeps one part of the value. A string key selects an object property (output or parameter names, as the baseline shows objects), a number selects an array element, several keys walk deeper, e.g. `["get", "lastFinalizeTimestamp"]` on the result of `miscData()`.',
  '',
  'Other operators of the same small language exist (`pipe`, `map`, other `format` type casters, …) and are documented in the discovery README; an edit that does not fit its value fails when the field runs.',
].join('\n')
