import { readFileSync, writeFileSync } from 'fs'
import { parseJsonc } from '@l2beat/shared-pure'
import { type GeneratedToken, Output, Source } from '../../../src/tokens/types'
import type { ScriptLogger } from './ScriptLogger'

export function readTokensFile(sourceFilePath: string, logger: ScriptLogger) {
  const sourceFile = readFileSync(sourceFilePath, 'utf-8')
  try {
    const parsed = parseJsonc<Record<string, string>>(sourceFile)
    return Source.parse(parsed)
  } catch (e) {
    console.error(e)
    logger.assert(false, 'Cannot parse tokens.jsonc')
  }
}

export function readGeneratedFile(
  outputFilePath: string,
  logger: ScriptLogger,
) {
  const outputFile = readFileSync(outputFilePath, 'utf-8')
  try {
    const output = Output.parse(JSON.parse(outputFile))
    return output
  } catch (e) {
    console.error(e)
    logger.assert(false, 'Cannot parse generated.json')
  }
}

export function saveResults(outputFilePath: string, result: GeneratedToken[]) {
  const comment = 'This file was autogenerated. Please do not edit it manually.'
  const outputJson = JSON.stringify(
    {
      comment: comment,
      tokens: result,
    },
    null,
    2,
  )
  writeFileSync(outputFilePath, outputJson + '\n')
}
