import { config as dotenv } from 'dotenv'
import { providers } from 'ethers'
import { writeFile } from 'fs/promises'

import { getEnv } from '../checkVerifiedContracts/utils'
import { getOmnichain } from './getOmnichain'

async function main() {
  const provider = new providers.AlchemyProvider(
    'homestead',
    getEnv('CONFIG_ALCHEMY_API_KEY'),
  )

  const escrows = await getOmnichain(provider)

  const comment =
    'This file was autogenerated. Do not modify it by hand, instead use: yarn update-omnichain'

  await writeFile(
    'src/bridges/lzOmnichain-config.json',
    JSON.stringify({ comment, escrows }, null, 2),
  )
}

dotenv()
main().catch((e) => {
  console.error(e)
  process.exit(1)
})
