// Generated by `l2b crops-attest --execute`. Do not edit by hand.
//
// A cache of onchain state, not the source of truth: `l2b crops-verify` reads
// every uid back from EAS and fails if anything here has drifted. It is
// committed so the API can serve attestation references without an RPC call on
// the request path.
export const CROP_ATTESTATION_DATA = {
  sepolia: {
    network: 'sepolia' as const,
    attester: '0xb55D684Be25227b722a007F6bB8AA706ca18BdDA',
    firstBlock: 11515690,
    live: [
      {
        projectId: 'aztecnetwork',
        uid: '0x1c10224ed1156f3fc3a2e6edd68de09707a6a19067c9afdee7a474c09a90258a',
        revision: 1,
        reviewedAt: 1787063642,
        evaluationHash:
          '0xdc1e05d88e4222ff2ae9bb2392a890a7e9b8bec8d6be502e67e6f814f47e7fd6',
        txHash:
          '0x47ba4ea88c71d3a3aec0e637c859e7d0c44e3bfdd20062f01838f99c642cd9d3',
        block: 11515690,
      },
      {
        projectId: 'ethscriptions',
        uid: '0x3967bd2e9b7aee7f2a8560fab7150785aa37870ddfcb8adefb9eb9b81661881c',
        revision: 1,
        reviewedAt: 1787063642,
        evaluationHash:
          '0x480c04499db3f72245e1751305cfc7e2408ee8f05c343e0347c015fd840c4f91',
        txHash:
          '0x47ba4ea88c71d3a3aec0e637c859e7d0c44e3bfdd20062f01838f99c642cd9d3',
        block: 11515690,
      },
      {
        projectId: 'tornado-cash',
        uid: '0x919b5c2ac5614641055d628a4e5bee699192b600a5d3416ccda6128f26636902',
        revision: 1,
        reviewedAt: 1787063642,
        evaluationHash:
          '0x9282869e066aaba71865e4380d9889f431af6ccf72e8d66ae60ca1afec54faf5',
        txHash:
          '0x47ba4ea88c71d3a3aec0e637c859e7d0c44e3bfdd20062f01838f99c642cd9d3',
        block: 11515690,
      },
      {
        projectId: 'umbra',
        uid: '0xdd71d079ec50708187a0e8f1e154f777a3259180a38d410bb3daeb252c77acc1',
        revision: 1,
        reviewedAt: 1787063642,
        evaluationHash:
          '0xa403c3fa9de24feb753163bc3eee0315371d581e70a0150e86bd4729d3ba9f0c',
        txHash:
          '0x47ba4ea88c71d3a3aec0e637c859e7d0c44e3bfdd20062f01838f99c642cd9d3',
        block: 11515690,
      },
      {
        projectId: 'uniswapv3',
        uid: '0x27f8f5b21a8c666633f014741ee6ad5fc6c7da6a16f66c121811a85eb6ec4901',
        revision: 1,
        reviewedAt: 1787063642,
        evaluationHash:
          '0xda01ee138884222e5685c02b576de055b924876010203e04cb28d051d24d271d',
        txHash:
          '0x47ba4ea88c71d3a3aec0e637c859e7d0c44e3bfdd20062f01838f99c642cd9d3',
        block: 11515690,
      },
    ],
    revoked: [],
  },
}
