import { writeFile } from 'fs/promises'
import { fetchMultichainConfig } from './fetchMultichainConfig'
import { generateFinalConfig } from './generateFinalConfig'
import { generateIntermediateConfig } from './generateIntermediateConfig'

main()
async function main() {
  const config = await fetchMultichainConfig()
  const intermediate = generateIntermediateConfig(config)

  const comment =
    'This file was autogenerated. Do not modify it by hand, instead use: yarn update-multichain'

  writeFile(
    'scripts/multichain/intermediate.json',
    JSON.stringify({ comment, ...intermediate }, null, 2),
  )
  const final = generateFinalConfig(intermediate)
  writeFile(
    'src/bridges/multichain-config.json',
    JSON.stringify({ comment, ...final }, null, 2),
  )
}
