ARG TURBO_TEAM
ARG TURBO_TOKEN
ARG COREPACK_VERSION="^0.31.0"

FROM node:22 AS base
ARG TURBO_TEAM
ARG TURBO_TOKEN
ARG COREPACK_VERSION
ENV TURBO_TEAM=$TURBO_TEAM
ENV TURBO_TOKEN=$TURBO_TOKEN
ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"
RUN npm i -g corepack@${COREPACK_VERSION} && corepack enable pnpm
RUN pnpm add -g turbo
WORKDIR /app/
COPY . .
RUN pnpm install --frozen-lockfile && pnpm build:frontend-rewrite
WORKDIR /app/packages/frontend/
