import { ProjectId, UnixTime } from '@l2beat/shared-pure'
import { DaEconomicSecurityRisk, DaFraudDetectionRisk } from '../../common'
import { linkByDA } from '../../common/linkByDA'
import type { BaseProject } from '../../types'

export const celestia: BaseProject = {
  id: ProjectId('celestia'),
  slug: 'celestia',
  name: 'Celestia',
  shortName: undefined,
  addedAt: UnixTime.fromDate(new Date('2024-09-03')),
  // tags
  isDaLayer: true,
  // data
  statuses: {
    yellowWarning: undefined,
    redWarning: undefined,
    emergencyWarning: undefined,
    reviewStatus: undefined,
    unverifiedContracts: [],
  },
  display: {
    description:
      'Celestia is a modular data availability network that allows L2s to post arbitrary data as blobs.',
    links: {
      websites: ['https://celestia.org/'],
      documentation: ['https://docs.celestia.org/'],
      repositories: ['https://github.com/celestiaorg'],
      explorers: ['https://celenium.io/'],
      socialMedia: [
        'https://x.com/Celestia',
        'https://discord.com/invite/YsnTPcSfWQ',
        'https://t.me/CelestiaCommunity',
      ],
    },
    badges: [],
  },
  daLayer: {
    type: 'Public Blockchain',
    systemCategory: 'public',
    technology: {
      description: `
      ## Architecture

      ![Celestia architecture](/images/da-layer-technology/celestia/architecture.png#center)

      ## Consensus
      Celestia uses CometBTF, the canonical implementation of Tendermint consensus protocol. The consensus protocol is fork-free by construction under an honest majority of stake assumption.
      Celestia achieves finality at each block, with an average time between blocks of 6 seconds.
      ## Blobs
      In Celestia, blobs are user-submitted data that do not modify the blockchain state.  
      Each blob has two components, one is a binary object of raw data bytes, and the other is the namespace of the specific application for which the blob data is intended for.\n

      ![Blobs](/images/da-layer-technology/celestia/blobs.png#center)

      All data posted in a Celestia blob is divided into chunks of fixed size, called shares, and each blob is arranged in a k * k matrix of shares. Currently k = 64, for a total of 4096 shares.\n

      ![Blobs matrix](/images/da-layer-technology/celestia/blobs-matrix.png#center)

      Celestia shares' rows and columns are erasure-coded into a 2k * 2k matrix and committed to in a Namespaced Merkle Trees (NMTs), a version of a standard Merkle tree using a namespaced hash function. 
      In NMTs, every node in the tree includes the range of namespaces of all its child nodes, allowing applications to request and retrieve data for a specific namespace sub-tree while maintaining all functionalities (e.g., inclusion and range proofs) of a standard Merkle tree.\n

      ![Matrix proofs](/images/da-layer-technology/celestia/matrix-proofs.png#center)

      Ultimately, a single data root (availableDataRoot) of the Merkle tree is computed with the row and column roots as leaves. This data root is included in the block header as the root of commitments to erasure-coded data so that individual shares in the matrix can be proven to belong to a single data root.\n

      ![Data root](/images/da-layer-technology/celestia/data-root.png#center)

      ## Data Availability Sampling (DAS)

      To ensure data availability, Celestia light nodes perform sampling on the 2k x 2k data matrix. Each light node randomly selects a set of unique coordinates within the extended matrix and requests the corresponding data shares and Merkle proofs from full nodes.
      Currently, a Celestia light node must perform a minimum of 16 samples before declaring that a block is available.
      This sampling rate ensures that given the minimum number of unavailable shares, a light client will sample at least one unavailable share with a 99% probability.\n
      For more details on DAS probabilistic analysis, see the Fraud and Data Availability Proofs paper.\n

      ![DAS](/images/da-layer-technology/celestia/das.png#center)

      ## Erasure Coding Proof
      Light nodes performing data availability sampling must have the guarantee that the sampled data is erasure coded correctly. In Celestia, light nodes can be notified of a maliciously encoded block through Bad Encoding Fraud Proofs (BEFPs). Full nodes receiving invalid erasure-coded data can generate a fraud-proof to be transmitted to all light and full nodes in the DA network. The proof is generated by full nodes reconstructing the original data from the block data, and verifying that the recomputed data root matches the data root of the block header. 
      Upon receiving and verifying the BEFP, all Celestia nodes should halt providing services (e.g., submitTx).

      ## L2s Data Availability
      L2s can post data to Celestia by submitting blobs through a payForBlobs transaction. The transaction can include data as a single blob or multiple blobs, with the total maximum size determined by the maximum block size. The transaction fee is determined by the size of the data and the current gas price. 
      Applications can then retrieve the data by querying the Celestia blockchain for the data root of the blob and the namespace of the application. The data can be reconstructed by querying the Celestia network for the shares of the data matrix and reconstructing the data using the erasure coding scheme.
      `,
      references: [
        {
          title: 'Celestia Specifications',
          url: 'https://celestiaorg.github.io/celestia-app/specs/index.html',
        },
        {
          title: 'Celestia Core - CometBFT',
          url: 'https://github.com/celestiaorg/celestia-core',
        },
        {
          title: 'Celestia Node - Data Retrieval',
          url: 'https://github.com/celestiaorg/celestia-node/blob/9ff58570ef86e505b718abfc755fd18643a2284c/share/eds/retriever.go#L60',
        },
        {
          title: 'Bad Encoding Fraud Proofs',
          url: 'https://github.com/celestiaorg/celestia-node/blob/main/docs/adr/adr-006-fraud-service.md',
        },
        {
          title: 'Fraud and Data Availability Proofs paper',
          url: 'https://arxiv.org/pdf/1809.09044',
        },
      ],
      risks: [
        {
          category: 'Funds can be lost if',
          text: `a dishonest supermajority of Celestia validators finalizes an unavailable block, and there aren't light nodes on the network verifying data availability, or they fail at social signaling unavailable data.`,
        },
        {
          category: 'Funds can be lost if',
          text: 'a dishonest supermajority of Celestia validators finalizes an unavailable block, and the light nodes on the network cannot collectively reconstruct the block.',
        },
      ],
    },
    usedWithoutBridgeIn: linkByDA({
      layer: ProjectId('celestia'),
      bridge: undefined,
    }),
    /*
      Node params sources:
      - unbondingPeriod, finality (time_iota_ms): https://celestiaorg.github.io/celestia-app/specs/params.html
      - pruningWindow: https://github.com/celestiaorg/CIPs/blob/main/cips/cip-004.md
      - block time: https://github.com/celestiaorg/celestia-app/blob/main/pkg/appconsts/consensus_consts.go
      - max block size: (DefaultMaxBytes) https://github.com/celestiaorg/celestia-app/blob/main/pkg/appconsts/initial_consts.go
    */
    consensusAlgorithm: {
      name: 'CometBFT',
      description: `CometBFT is the canonical implementation of the Tendermint consensus algorithm.
      CometBFT allows for a state transition machine to be written in any programming language, and it allows for secure replication across many machines.
      The consensus protocol is fork-free by construction under an honest majority of stake assumption.`,
      blockTime: 15, // goal block time, seconds
      consensusFinality: 1, // 1 second for tendermint, time_iota_ms
      unbondingPeriod: UnixTime.DAY * 21, // staking.UnbondingTime
    },
    dataAvailabilitySampling: {
      erasureCodingScheme: '2D Reed-Solomon',
      erasureCodingProof: 'Fraud proofs',
    },
    pruningWindow: 86400 * 30, // 30 days in seconds
    throughput: [
      {
        size: 8388608, // 8 MiB
        frequency: 6, // 6 seconds
        sinceTimestamp: 1738022400, // 2025-01-28,
      },
      {
        size: 1974272, // 1.88 MiB
        frequency: 6,
        sinceTimestamp: 1733961600, // 2024-12-12
      },
      {
        size: 1974272, // 1.88 MiB
        frequency: 12,
        sinceTimestamp: 1698710400, // 2023-10-31
      },
    ],
    finality: 6, // seconds
    risks: {
      economicSecurity: DaEconomicSecurityRisk.OnChainQuantifiable,
      fraudDetection: DaFraudDetectionRisk.DasWithNoBlobsReconstruction(true),
    },
    economicSecurity: {
      name: 'Celestia',
      token: {
        symbol: 'TIA',
        decimals: 6,
        coingeckoId: 'celestia',
      },
    },
    sovereignProjectsTrackingConfig: [
      {
        projectId: ProjectId('battle-for-blockchain'),
        name: 'Battle for Blockchain',
        daTrackingConfig: [
          {
            type: 'celestia',
            sinceBlock: 5047670,
            namespace: 'AAAAAAAAAAAAAAAAAAAAAAAAAKzFLTn1xOipecg=',
          },
        ],
      },
      {
        projectId: ProjectId('civitia'),
        name: 'Civitia',
        daTrackingConfig: [
          {
            type: 'celestia',
            sinceBlock: 4492300,
            namespace: 'AAAAAAAAAAAAAAAAAAAAAAAAAEwLOhV+kOUlUq4=',
          },
        ],
      },
      {
        projectId: ProjectId('clique'),
        name: 'Clique',
        daTrackingConfig: [
          {
            type: 'celestia',
            sinceBlock: 3161819,
            namespace: 'AAAAAAAAAAAAAAAAAAAAAAAAAAAAARQV7t6sd4A=',
          },
        ],
      },
      {
        projectId: ProjectId('echelon'),
        name: 'Echelon',
        daTrackingConfig: [
          {
            type: 'celestia',
            sinceBlock: 5659637,
            namespace: 'AAAAAAAAAAAAAAAAAAAAAAAAAItyY42OaTC/skE=',
          },
        ],
      },
      {
        projectId: ProjectId('echos'),
        name: 'Echos',
        daTrackingConfig: [
          {
            type: 'celestia',
            sinceBlock: 3161819,
            namespace: 'AAAAAAAAAAAAAAAAAAAAAAAAAAAAA/cZMN1XLG8=',
          },
        ],
      },
      {
        projectId: ProjectId('embr-fun'),
        name: 'Embr.fun',
        daTrackingConfig: [
          {
            type: 'celestia',
            sinceBlock: 5954601,
            namespace: 'AAAAAAAAAAAAAAAAAAAAAAAAAMbONmnisjTDz4I=',
          },
        ],
      },
      {
        projectId: ProjectId('flame'),
        name: 'Flame',
        daTrackingConfig: [
          {
            type: 'celestia',
            sinceBlock: 3161819,
            namespace: 'AAAAAAAAAAAAAAAAAAAAAAAAAL2dxfeNrJ+tg6Y=',
          },
        ],
      },
      {
        projectId: ProjectId('flynet'),
        name: 'Flynet',
        daTrackingConfig: [
          {
            type: 'celestia',
            sinceBlock: 5188001,
            namespace: 'AAAAAAAAAAAAAAAAAAAAAAAAAAAACyPE7Ql9zwA=',
          },
        ],
      },
      {
        projectId: ProjectId('forma'),
        name: 'Forma',
        daTrackingConfig: [
          {
            type: 'celestia',
            sinceBlock: 3161819,
            namespace: 'AAAAAAAAAAAAAAAAAAAAAAAAAKKnitomrCy/HoY=',
          },
        ],
      },
      {
        projectId: ProjectId('foundation-network'),
        name: 'Foundation Network',
        daTrackingConfig: [
          {
            type: 'celestia',
            sinceBlock: 3667737,
            namespace: 'AAAAAAAAAAAAAAAAAAAAAAAAAN/xAxpagCrjLVQ=',
          },
        ],
      },
      {
        projectId: ProjectId('hibachi'),
        name: 'Hibachi',
        daTrackingConfig: [
          {
            type: 'celestia',
            sinceBlock: 5979823,
            namespace: 'AAAAAAAAAAAAAAAAAAAAAAAAAABoaWJhY2hpLXM=',
          },
          {
            type: 'celestia',
            sinceBlock: 5981133,
            namespace: 'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAGhpYmFjaGk=',
          },
        ],
      },
      {
        projectId: ProjectId('ing'),
        name: 'ING',
        daTrackingConfig: [
          {
            type: 'celestia',
            sinceBlock: 5945453,
            namespace: 'AAAAAAAAAAAAAAAAAAAAAAAAALdhUSKgKHU0Zx0=',
          },
        ],
      },
      {
        projectId: ProjectId('inertia'),
        name: 'Inertia',
        daTrackingConfig: [
          {
            type: 'celestia',
            sinceBlock: 5941532,
            namespace: 'AAAAAAAAAAAAAAAAAAAAAAAAAEg2If2QGyq4ZRQ=',
          },
        ],
      },
      {
        projectId: ProjectId('intergaze'),
        name: 'Intergaze',
        daTrackingConfig: [
          {
            type: 'celestia',
            sinceBlock: 5748411,
            namespace: 'AAAAAAAAAAAAAAAAAAAAAAAAAIoZCJNLh1XvOZA=',
          },
        ],
      },
      {
        projectId: ProjectId('milkyway'),
        name: 'Milkyway',
        daTrackingConfig: [
          {
            type: 'celestia',
            sinceBlock: 5298640,
            namespace: 'AAAAAAAAAAAAAAAAAAAAAAAAAB2AZsEwLd1LLHk=',
          },
        ],
      },
      {
        projectId: ProjectId('onchain'),
        name: 'Onchain',
        daTrackingConfig: [
          {
            type: 'celestia',
            sinceBlock: 3161819,
            namespace: 'AAAAAAAAAAAAAAAAAAAAAAAAAAAABNfLrOLSCTY=',
          },
        ],
      },
      {
        projectId: ProjectId('perennial'),
        name: 'Perennial',
        daTrackingConfig: [
          {
            type: 'celestia',
            sinceBlock: 3886561,
            namespace: 'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAaToZYrE0tA=',
          },
        ],
      },
      {
        projectId: ProjectId('rave'),
        name: 'Rave',
        daTrackingConfig: [
          {
            type: 'celestia',
            sinceBlock: 5645296,
            namespace: 'AAAAAAAAAAAAAAAAAAAAAAAAAF45zaUciayEPXE=',
          },
        ],
      },
      {
        projectId: ProjectId('rena'),
        name: 'Rena',
        daTrackingConfig: [
          {
            type: 'celestia',
            sinceBlock: 5775045,
            namespace: 'AAAAAAAAAAAAAAAAAAAAAAAAAMxohfftlR5t59s=',
          },
        ],
      },
      {
        projectId: ProjectId('rivalz-network'),
        name: 'Rivalz Network',
        daTrackingConfig: [
          {
            type: 'celestia',
            sinceBlock: 4932528,
            namespace: 'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAMJ/xGlNMdE=',
          },
        ],
      },
      {
        projectId: ProjectId('yominet'),
        name: 'Yominet',
        daTrackingConfig: [
          {
            type: 'celestia',
            sinceBlock: 5966190,
            namespace: 'AAAAAAAAAAAAAAAAAAAAAAAAAFjh+OUc/ORU/0o=',
          },
        ],
      },
      {
        projectId: ProjectId('zaar'),
        name: 'Zaar',
        daTrackingConfig: [
          {
            type: 'celestia',
            sinceBlock: 5587852,
            namespace: 'AAAAAAAAAAAAAAAAAAAAAAAAAM8NBxiaOQwFwQc=',
          },
        ],
      },
    ],
  },
  milestones: [
    {
      title: 'Mainnet Launch',
      url: 'https://blog.celestia.org/celestia-mainnet-is-live/',
      date: '2023-10-31T00:00:00Z',
      description: 'Celestia mainnet launches.',
      type: 'general',
    },
    {
      title: 'Ginger upgrade',
      url: 'https://blog.celestia.org/ginger/',
      date: '2024-12-12T00:00:00Z',
      description:
        'Celestia Ginger upgrade cuts the block time in half from 12 to 6 seconds.',
      type: 'general',
    },
    {
      title: 'Block size increase to 8MB',
      url: 'https://x.com/celestia/status/1881756463317860430/',
      date: '2025-01-28T00:00:00Z',
      description:
        'Celestia onchain governance votes to increase the block size from 2MB to 8MB.',
      type: 'general',
    },
  ],
}
