-- AlterTable
ALTER TABLE "FlatSources" ADD COLUMN     "timestamp" TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP;

-- AlterTable
ALTER TABLE "UpdateDiff" ADD COLUMN     "diffBaseTimestamp" TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN     "diffHeadTimestamp" TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP;

-- AlterTable
ALTER TABLE "UpdateNotifier" ADD COLUMN     "timestamp" TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP;
