import type {
  CropsAddressMatch,
  IndexedProject,
} from './garden/buildCropsAddressIndex'
import { buildCropsAddressIndex } from './garden/buildCropsAddressIndex'
import type { CropsSourceProject } from './garden/resolveCropsProjects'
import {
  resolveCropsProjects,
  toCropsSummary,
} from './garden/resolveCropsProjects'
import { buildOpenApiDocument } from './openapi'
import type {
  AddressMatch,
  CropsApiProject,
  CropsAttestationsMeta,
  Stamp,
} from './schemas'

/** A project with crops plus whatever the address index and page path need. */
export interface CropsProject extends CropsSourceProject, IndexedProject {}

/** Long chain name -> EIP-155 chain id. */
export type ChainIdByName = Record<string, number>

export interface GeneratorInput {
  projects: CropsProject[]
  chains: ChainIdByName
  ledger: CropsAttestationsMeta
  commit: string
  /** Unix seconds. */
  generatedAt: number
}

export interface GeneratedFile {
  /** Relative to the site root, no leading slash. */
  path: string
  body: unknown
}

/**
 * The whole API as a pure function of config and ledger, so it can be tested
 * with fixtures and regenerated byte-for-byte from the same commit.
 */
export function generateCropsSite(input: GeneratorInput): GeneratedFile[] {
  const stamp: Stamp = {
    attestations: input.ledger,
    generatedAt: input.generatedAt,
    commit: input.commit,
  }
  const projects = resolveCropsProjects(input.projects, input.ledger)
  const files: GeneratedFile[] = [
    { path: 'v1/crops.json', body: { ...stamp, projects } },
    ...projectFiles(projects, stamp),
    ...addressFiles(input, projects, stamp),
    { path: 'v1/openapi.json', body: buildOpenApiDocument(input.ledger) },
  ]
  return files.sort((a, b) => a.path.localeCompare(b.path))
}

function projectFiles(
  projects: CropsApiProject[],
  stamp: Stamp,
): GeneratedFile[] {
  return projects.flatMap((project) =>
    [...new Set([project.id, project.slug])].map((key) => ({
      path: `v1/project/${key}.json`,
      body: { ...stamp, ...project },
    })),
  )
}

function addressFiles(
  input: GeneratorInput,
  projects: CropsApiProject[],
  stamp: Stamp,
): GeneratedFile[] {
  const projectById = new Map(projects.map((x) => [x.id, x]))
  return buildCropsAddressIndex(input.projects).map((entry) => {
    const chainId = input.chains[entry.chain]
    if (chainId === undefined) {
      throw new Error(
        `Chain ${entry.chain} has no chain id, but ${entry.address} is reviewed`,
      )
    }
    const address = entry.address.toLowerCase()
    return {
      path: `v1/address/${chainId}/${address}.json`,
      body: {
        ...stamp,
        chainId,
        address,
        matches: entry.matches.map((match) =>
          toAddressMatch(match, projectById),
        ),
      },
    }
  })
}

function toAddressMatch(
  match: CropsAddressMatch,
  projectById: Map<string, CropsApiProject>,
): AddressMatch {
  const project = projectById.get(match.projectId)
  if (!project) {
    throw new Error(`Indexed project ${match.projectId} has no crops`)
  }
  return {
    id: project.id,
    slug: project.slug,
    name: project.name,
    href: project.href,
    contractName: match.targetName,
    crops: toCropsSummary(project.crops),
    attestation: project.attestation
      ? { uid: project.attestation.uid, revision: project.attestation.revision }
      : null,
  }
}
