import {
  type AddressMatch,
  type AddressResponse,
  type CropsApiProject,
  type CropsApiRouteKey,
  type CropsApiStamp,
  type CropsAttestationsMeta,
  type CropsResponse,
  type CropsSourceProject,
  type ProjectResponse,
  resolveCropsProject,
  toCropsSummary,
} from './api'
import {
  buildCropsAddressIndex,
  type IndexedProject,
} from './buildCropsAddressIndex'

/** A project with crops plus whatever the address index and page path need. */
export interface CropsApiInputProject
  extends CropsSourceProject,
    IndexedProject {}

/** Long chain name -> EIP-155 chain id. */
export type ChainIdByName = Record<string, number>

export interface CropsApiInput {
  projects: CropsApiInputProject[]
  chains: ChainIdByName
  ledger: CropsAttestationsMeta
  commit: string
  /** Unix seconds. */
  generatedAt: number
}

/** One JSON file of the API, tagged with the route that publishes it. */
export type CropsApiFile = { path: string } & (
  | { route: 'crops'; body: CropsResponse }
  | { route: 'project'; body: ProjectResponse }
  | { route: 'address'; body: AddressResponse }
)

export type CropsApiFileFor<K extends CropsApiRouteKey> = Extract<
  CropsApiFile,
  { route: K }
>

/**
 * The data files of the API as a pure function of config and ledger, so they
 * can be tested with fixtures, regenerated byte-for-byte from the same commit,
 * and shown as examples on the website without a second implementation.
 */
export function generateCropsApiFiles(input: CropsApiInput): CropsApiFile[] {
  const stamp: CropsApiStamp = {
    attestations: input.ledger,
    generatedAt: input.generatedAt,
    commit: input.commit,
  }
  const projects = input.projects
    .map((source) => ({
      ...source,
      api: resolveCropsProject(source, input.ledger),
    }))
    .sort((a, b) => a.id.localeCompare(b.id))
  const files: CropsApiFile[] = [
    {
      route: 'crops',
      path: 'v1/crops.json',
      body: { ...stamp, projects: projects.map((x) => x.api) },
    },
    ...projectFiles(
      projects.map((x) => x.api),
      stamp,
    ),
    ...addressFiles(projects, input.chains, stamp),
  ]
  return files.sort((a, b) => a.path.localeCompare(b.path))
}

function projectFiles(
  projects: CropsApiProject[],
  stamp: CropsApiStamp,
): CropsApiFileFor<'project'>[] {
  return projects.flatMap((project) =>
    [...new Set([project.id, project.slug])].map((key) => ({
      route: 'project' as const,
      path: `v1/project/${key}.json`,
      body: { ...stamp, ...project },
    })),
  )
}

function addressFiles(
  projects: (IndexedProject & { api: CropsApiProject })[],
  chains: ChainIdByName,
  stamp: CropsApiStamp,
): CropsApiFileFor<'address'>[] {
  return buildCropsAddressIndex(projects).map((entry) => {
    const chainId = chains[entry.chain]
    if (chainId === undefined) {
      throw new Error(
        `Chain ${entry.chain} has no chain id, but ${entry.address} is reviewed`,
      )
    }
    const address = entry.address.toLowerCase()
    return {
      route: 'address',
      path: `v1/address/${chainId}/${address}.json`,
      body: {
        ...stamp,
        chainId,
        address,
        matches: entry.matches.map((match) =>
          toAddressMatch(match.project.api, match.targetName),
        ),
      },
    }
  })
}

function toAddressMatch(
  project: CropsApiProject,
  contractName: string,
): AddressMatch {
  return {
    id: project.id,
    slug: project.slug,
    name: project.name,
    href: project.href,
    contractName,
    crops: toCropsSummary(project.crops),
    attestation: project.attestation
      ? { uid: project.attestation.uid, revision: project.attestation.revision }
      : null,
  }
}
