-- AlterTable
ALTER TABLE "FlatSources" ALTER COLUMN "timestamp" SET DEFAULT CURRENT_TIMESTAMP;

-- AlterTable
ALTER TABLE "UpdateDiff" ALTER COLUMN "diffBaseTimestamp" SET DEFAULT CURRENT_TIMESTAMP,
ALTER COLUMN "diffHeadTimestamp" SET DEFAULT CURRENT_TIMESTAMP;

-- AlterTable
ALTER TABLE "UpdateNotifier" ALTER COLUMN "timestamp" SET DEFAULT CURRENT_TIMESTAMP;
