export interface InteropChain {
  id: string
  name: string
  type: 'evm'
  display: string
  color: string
  iconSlug?: string
  explorerUrl: string
}

export const INTEROP_CHAINS: InteropChain[] = [
  {
    id: 'ethereum',
    name: 'Ethereum',
    type: 'evm',
    display: 'ETH',
    color: '#627EEA',
    explorerUrl: 'https://etherscan.io',
  },
  {
    id: 'arbitrum',
    name: 'Arbitrum One',
    type: 'evm',
    display: 'ARB',
    color: '#28A0F0',
    explorerUrl: 'https://arbiscan.io',
  },
  {
    id: 'base',
    name: 'Base',
    type: 'evm',
    display: 'BASE',
    color: '#0052FF',
    explorerUrl: 'https://basescan.org',
  },
  {
    id: 'optimism',
    name: 'OP Mainnet',
    iconSlug: 'op-mainnet',
    type: 'evm',
    display: 'OP',
    color: '#FF0420',
    explorerUrl: 'https://optimistic.etherscan.io',
  },
  {
    id: 'apechain',
    name: 'ApeChain',
    type: 'evm',
    display: 'APE',
    color: '#0054FA',
    explorerUrl: 'https://apescan.io',
  },
  {
    id: 'polygonpos',
    iconSlug: 'polygon-pos',
    name: 'Polygon PoS',
    type: 'evm',
    display: 'POL',
    color: '#8247E5',
    explorerUrl: 'https://polygonscan.com',
  },
  {
    id: 'zksync2',
    iconSlug: 'zksync-era',
    name: 'ZKsync Era',
    type: 'evm',
    display: 'ZK',
    color: '#4E529A',
    explorerUrl: 'https://explorer.zksync.io',
  },
  {
    id: 'abstract',
    name: 'Abstract',
    type: 'evm',
    display: 'ABS',
    color: '#00FF94',
    explorerUrl: 'https://abscan.org',
  },
  {
    id: 'katana',
    iconSlug: 'katana',
    name: 'Katana',
    type: 'evm',
    display: 'KAT',
    color: '#E11D48',
    explorerUrl: 'https://katanascan.com',
  },
  {
    id: 'bsc',
    name: 'BNB Smart Chain',
    type: 'evm',
    display: 'BSC',
    color: '#F0B90B',
    explorerUrl: 'https://bscscan.com',
  },
  {
    id: 'solana',
    name: 'Solana',
    type: 'evm',
    display: 'SOL',
    color: '#9945FF',
    explorerUrl: 'https://solscan.io',
  },
  {
    id: 'starknet',
    name: 'Starknet',
    type: 'evm',
    display: 'STRK',
    color: '#EC796B',
    explorerUrl: 'https://starkscan.co',
  },
  {
    id: 'ink',
    name: 'Ink',
    type: 'evm',
    display: 'INK',
    color: '#B87FFF',
    explorerUrl: 'https://explorer.inkonchain.com',
  },
  {
    id: 'megaeth',
    name: 'MegaETH',
    type: 'evm',
    display: 'MEGA',
    color: '#FF6B00',
    explorerUrl: 'https://megaeth.blockscout.com',
  },
  {
    id: 'worldchain',
    iconSlug: 'world',
    name: 'World Chain',
    type: 'evm',
    display: 'WORLD',
    color: '#1DC99E',
    explorerUrl: 'https://worldscan.org',
  },
  {
    id: 'celo',
    name: 'Celo',
    type: 'evm',
    display: 'CELO',
    color: '#FCFF52',
    explorerUrl: 'https://celoscan.io',
  },
  {
    id: 'unichain',
    name: 'Unichain',
    type: 'evm',
    display: 'UNI',
    color: '#FF007A',
    explorerUrl: 'https://uniscan.xyz',
  },
  {
    id: 'forknet',
    iconSlug: 'forknet',
    name: 'Forknet',
    type: 'evm',
    display: 'FORK',
    color: '#8B5CF6',
    explorerUrl: 'https://forkscan.org',
  },
  {
    id: 'linea',
    name: 'Linea',
    type: 'evm',
    display: 'LINEA',
    color: '#61DFFF',
    explorerUrl: 'https://lineascan.build',
  },
  {
    id: 'avalanche',
    name: 'Avalanche',
    type: 'evm',
    display: 'AVAX',
    color: '#E84142',
    explorerUrl: 'https://snowtrace.io',
  },
  {
    id: 'hyperevm',
    name: 'HyperEVM',
    type: 'evm',
    display: 'HYPER',
    color: '#3CFF72',
    explorerUrl: 'https://hyperevmscan.io',
  },
  {
    id: 'tempo',
    name: 'Tempo',
    type: 'evm',
    display: 'TMP',
    color: '#7C3AED',
    explorerUrl: 'https://explore.tempo.xyz',
  },
  {
    id: 'monad',
    name: 'Monad',
    type: 'evm',
    display: 'MON',
    color: '#836EF9',
    explorerUrl: 'https://monadscan.com',
  },
] as const

export const INTEROP_ONE_SIDED_CHAINS = ['solana'] as const
