[book]
authors = ["Luca Donno"]
language = "en"
multilingual = false
src = "specs"
title = "L2 code walkthroughs"

[output.html]
additional-js = ["specs/static/solidity.min.js"]
default-theme = "ayu"
