import { expect } from 'earl'
import {
  createPrivacyAnonymitySetConfigurationId,
  stringifyPrivacyConfigurationParams,
} from './createPrivacyConfigurationId'

describe(createPrivacyAnonymitySetConfigurationId.name, () => {
  it('matches the id generated by the original backend implementation', () => {
    expect(
      createPrivacyAnonymitySetConfigurationId({
        projectId: 'project-1',
        bucketId: 'bucket-1',
        chain: 'ethereum',
        address: '0x1111111111111111111111111111111111111111',
        event: `0x${'aa'.repeat(32)}`,
        extractor: 'fixedAmount',
        params: { amount: '1000000000000000000' },
      }),
    ).toEqual('c33ffb1b7442')
  })

  it('serializes parameters in key order', () => {
    expect(stringifyPrivacyConfigurationParams({ z: 1, a: 'two' })).toEqual(
      'a=two,z=1',
    )
  })
})
