export type ProjectSectionId =
  | 'chart'
  | 'detailed-description'
  | 'milestones'
  | 'knowledge-nuggets'
  | 'risk-analysis'
  | 'technology'
  | 'state-derivation'
  | 'state-validation'
  | 'operator'
  | 'withdrawals'
  | 'other-considerations'
  | 'permissions'
  | 'contracts'
  | 'stage'
