/**
 * Projects the canonical ossification dataset curve release into the compact
 * runtime input used by the frontend.
 *
 * The only accepted input is ../ossification-dataset/dist/latest/curve.json,
 * shaped by ../ossification-dataset/schema/release-curve.schema.json. There is
 * intentionally no fallback for the legacy in-repo incident or curve formats.
 *
 * Usage:
 *   pnpm tsx scripts/ossification-incidents-curve.ts
 *   pnpm tsx scripts/ossification-incidents-curve.ts --check
 */
import { execFileSync } from 'child_process'
import { readFileSync, writeFileSync } from 'fs'
import path from 'path'

const DATASET_ROOT = path.resolve(__dirname, '../../../../ossification-dataset')
const RELEASE_PATH = path.join(DATASET_ROOT, 'dist/latest/curve.json')
const SCHEMA_PATH = path.join(DATASET_ROOT, 'schema/release-curve.schema.json')
const OUTPUT_PATH = path.join(
  __dirname,
  '../src/server/features/projects/ossification/ossificationCurve.ts',
)

function main() {
  const args = process.argv.slice(2)
  const check = args.length === 1 && args[0] === '--check'
  if (args.length > 0 && !check) {
    throw new Error('Usage: ossification-incidents-curve.ts [--check]')
  }

  const release = readObject(RELEASE_PATH)
  const schema = readObject(SCHEMA_PATH)
  const ageKnots = readCanonicalAgeKnots(release, schema)
  const revision = execFileSync(
    'git',
    ['-C', DATASET_ROOT, 'rev-parse', 'HEAD'],
    { encoding: 'utf8' },
  ).trim()
  const output = renderOutput(ageKnots, revision)

  if (check) {
    if (readFileSync(OUTPUT_PATH, 'utf8') !== output) {
      throw new Error(
        `${OUTPUT_PATH} does not match the checked-out ossification dataset release`,
      )
    }
    console.log(
      `curve is current: ossification-dataset@${revision}, n=${ageKnots.length}`,
    )
    return
  }

  writeFileSync(OUTPUT_PATH, output)
  console.log(
    `wrote ${OUTPUT_PATH}\nossification-dataset@${revision}, n=${ageKnots.length}`,
  )
}

function readCanonicalAgeKnots(
  release: Record<string, unknown>,
  schema: Record<string, unknown>,
): number[] {
  if (schema.additionalProperties !== false) {
    throw new Error('Curve schema must reject additional top-level properties')
  }

  const properties = asObject(schema.properties, 'schema.properties')
  const required = asStringArray(schema.required, 'schema.required')
  for (const property of required) {
    if (!(property in release)) {
      throw new Error(`Curve release is missing required property ${property}`)
    }
  }
  for (const property of Object.keys(release)) {
    if (!(property in properties)) {
      throw new Error(`Curve release has unknown property ${property}`)
    }
  }

  assertSchemaConstant(release, properties, '$schema')
  assertSchemaConstant(release, properties, 'formatVersion')

  const ageKnots = asIntegerArray(release.ageKnots, 'release.ageKnots')
  for (let i = 0; i < ageKnots.length; i++) {
    const age = ageKnots[i] ?? 0
    if (age < 0) {
      throw new Error(`release.ageKnots[${i}] must be non-negative`)
    }
    if (i > 0 && age < (ageKnots[i - 1] ?? 0)) {
      throw new Error('release.ageKnots must be sorted ascending')
    }
  }

  const observations = asArray(release.observations, 'release.observations')
  if (observations.length !== ageKnots.length) {
    throw new Error('release.observations and release.ageKnots must align')
  }
  for (let i = 0; i < observations.length; i++) {
    const observation = asObject(observations[i], `release.observations[${i}]`)
    if (
      asInteger(observation.codeAgeSeconds, 'codeAgeSeconds') !== ageKnots[i]
    ) {
      throw new Error(
        `release.observations[${i}].codeAgeSeconds does not match ageKnots`,
      )
    }
  }

  const counts = asObject(release.counts, 'release.counts')
  if (
    asInteger(counts.curveObservations, 'release.counts.curveObservations') !==
    ageKnots.length
  ) {
    throw new Error('release.counts.curveObservations does not match ageKnots')
  }

  return ageKnots
}

function assertSchemaConstant(
  release: Record<string, unknown>,
  properties: Record<string, unknown>,
  property: '$schema' | 'formatVersion',
) {
  const propertySchema = asObject(
    properties[property],
    `schema.properties.${property}`,
  )
  if (release[property] !== propertySchema.const) {
    throw new Error(`Curve release has unsupported ${property}`)
  }
}

function renderOutput(ageKnots: number[], revision: string): string {
  return `/**
 * GENERATED by scripts/ossification-incidents-curve.ts — do not edit by hand.
 *
 * Source: ossification-dataset@${revision}
 * Canonical input: dist/latest/curve.json, validated against
 * schema/release-curve.schema.json by the dataset repository. Only the sorted
 * age knots are projected because the remaining release fields are not runtime
 * inputs to the score.
 */
// biome-ignore format: preserve the canonical ageKnots serialization
export const OSSIFICATION_CURVE_AGE_KNOTS = ${JSON.stringify(ageKnots)} as const
`
}

function readObject(file: string): Record<string, unknown> {
  return asObject(JSON.parse(readFileSync(file, 'utf8')), file)
}

function asObject(value: unknown, label: string): Record<string, unknown> {
  if (value === null || typeof value !== 'object' || Array.isArray(value)) {
    throw new Error(`${label} must be an object`)
  }
  return value as Record<string, unknown>
}

function asArray(value: unknown, label: string): unknown[] {
  if (!Array.isArray(value)) {
    throw new Error(`${label} must be an array`)
  }
  return value
}

function asStringArray(value: unknown, label: string): string[] {
  const array = asArray(value, label)
  if (!array.every((item) => typeof item === 'string')) {
    throw new Error(`${label} must contain only strings`)
  }
  return array as string[]
}

function asIntegerArray(value: unknown, label: string): number[] {
  return asArray(value, label).map((item, i) =>
    asInteger(item, `${label}[${i}]`),
  )
}

function asInteger(value: unknown, label: string): number {
  if (!Number.isSafeInteger(value)) {
    throw new Error(`${label} must be a safe integer`)
  }
  return value as number
}

main()
