/**
 * Generates the versioned empirical exploit-age curve that defines the
 * ossification score: score = share of recorded code-bug exploits whose
 * exploited code was younger than the perimeter's current age.
 *
 * Inputs (all committed, all onchain-verified by their producing scripts):
 *   - ossification-incidents.data.json + .curated-results.json
 *     (hand-curated incidents; results regenerated via
 *      `ossification-incidents.ts --json`)
 *   - ossification-incidents.registry.json + .batch-results.json
 *     (DeFiHackLabs-extracted incidents, classified with per-row evidence)
 *
 * Merge rules match the backtest report: code-bug rows only, measured ages
 * only, duplicates by (chain, victim contract) deduped with the curated row
 * winning.
 *
 * Output: src/server/features/projects/ossification/ossificationCurve.ts —
 * the sorted age knots (seconds) consumed by getOssificationFactor. Bump
 * `version` whenever the dataset changes; score changes must be deliberate,
 * versioned releases, never silent drift.
 *
 * Usage: npx tsx scripts/ossification-incidents-curve.ts
 */
import { readFileSync, writeFileSync } from 'fs'
import path from 'path'

const SECONDS_PER_YEAR = 365 * 24 * 60 * 60

interface CuratedIncident {
  name: string
  chain: string
  category: string
  contract: string | null
}
interface CuratedResult {
  name: string
  chain: string
  status: string
  ageDays?: number
}
interface RegistryRow {
  source: string
  chain: string
  contract: string
  category?: string
}
interface BatchResult {
  status: string
  ageDays?: number
  source: string
}

function main() {
  const dir = __dirname
  const read = (f: string) =>
    JSON.parse(readFileSync(path.join(dir, f), 'utf-8'))

  const curated = (
    read('ossification-incidents.data.json') as { incidents: CuratedIncident[] }
  ).incidents
  const curatedResults = read(
    'ossification-incidents.curated-results.json',
  ) as CuratedResult[]
  const registry = (
    read('ossification-incidents.registry.json') as { rows: RegistryRow[] }
  ).rows
  const batch = read('ossification-incidents.batch-results.json') as Record<
    string,
    BatchResult
  >

  const curatedByName = new Map(curated.map((i) => [i.name, i]))
  const seen = new Set<string>()
  const ageSeconds: number[] = []

  for (const r of curatedResults) {
    const inc = curatedByName.get(r.name)
    if (!inc || r.status !== 'OK' || inc.category !== 'code-bug') continue
    if (inc.contract) seen.add(`${r.chain}:${inc.contract.toLowerCase()}`)
    ageSeconds.push((r.ageDays ?? 0) * 24 * 60 * 60)
  }
  const registryBySource = new Map(registry.map((r) => [r.source, r]))
  for (const r of Object.values(batch)) {
    const reg = registryBySource.get(r.source)
    if (!reg || r.status !== 'OK' || reg.category !== 'code-bug') continue
    const key = `${reg.chain}:${reg.contract.toLowerCase()}`
    if (seen.has(key)) continue
    seen.add(key)
    ageSeconds.push((r.ageDays ?? 0) * 24 * 60 * 60)
  }

  ageSeconds.sort((a, b) => a - b)
  const knots = ageSeconds.map((s) => Math.round(s))
  const version = '2026-08'

  const out = `/**
 * GENERATED by scripts/ossification-incidents-curve.ts — do not edit by hand.
 *
 * The empirical exploit-age curve defining the ossification score: the sorted
 * ages (seconds since last change) of the exploited code in every measured
 * code-bug incident of the published dataset. The score is the interpolated
 * percentile of the perimeter's age within these knots: "this perimeter has
 * outlived the code age of N% of recorded code-bug exploits."
 *
 * Dataset releases are deliberate and versioned; regenerate only alongside a
 * dataset update and record the change.
 */
export const OSSIFICATION_CURVE = {
  version: '${version}',
  n: ${knots.length},
  /** Sorted exploited-code ages at incident time, in seconds. */
  ageKnots: ${JSON.stringify(knots)},
} as const
`
  const outPath = path.join(
    dir,
    '../src/server/features/projects/ossification/ossificationCurve.ts',
  )
  writeFileSync(outPath, out)
  const yrs = knots.map((k) => k / SECONDS_PER_YEAR)
  console.log(
    `wrote ${outPath}\nversion ${version}, n=${knots.length}, median ${(
      (yrs[Math.floor(yrs.length / 2)] ?? 0) * 12
    ).toFixed(1)}mo, max ${(yrs.at(-1) ?? 0).toFixed(2)}y`,
  )
}

main()
