export {
  MIN_NON_ZERO_HISTORY_POINTS,
  Z_CLASSIC_THRESHOLD,
  Z_ROBUST_THRESHOLD,
  Z_WINDOW_DAYS,
} from '../zScore'

export const FLAT_LINE_WINDOW_DAYS = 3

export const MIN_BASELINE_COUNT_PER_DAY = 10
export const MIN_BASELINE_VOLUME_USD_PER_DAY = 10_000
export const MIN_VOLUME_IDENTIFICATION_RATE = 0.5

export const RATIO_DROP_THRESHOLD = 0.1
export const RATIO_COUNT_SPIKE_THRESHOLD = 1.9
export const RATIO_VOLUME_SPIKE_THRESHOLD = 10

export const SIDE_MISMATCH_DIFF_PERCENT = 30
export const SIDE_MISMATCH_MIN_VOLUME_USD = 500_000

export const VALUE_DIFF_THRESHOLD_PERCENT = 15
export const MINIMUM_SIDE_VALUE_USD_THRESHOLD = 50
export const EXTREME_VALUE_RATIO_THRESHOLD = 5
