import './globals.css'

import type { Metadata } from 'next'
import { Roboto, Roboto_Serif } from 'next/font/google'

import { Navbar } from '~/components/navbar/Navbar'
import { cn } from '~/utils/cn'

const roboto = Roboto({
  subsets: ['latin'],
  variable: '--font-roboto',
  weight: ['400', '500', '700'],
})

const robotoSerif = Roboto_Serif({
  subsets: ['latin'],
  variable: '--font-roboto-serif',
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
  style: ['italic', 'normal'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" className="dark">
      <body className={cn(roboto.variable, robotoSerif.variable)}>
        <Navbar />
        {children}
      </body>
    </html>
  )
}
