import './globals.css'

import type { Metadata } from 'next'
import { Roboto, Roboto_Serif } from 'next/font/google'
import { ThemeProvider } from 'next-themes'

import { Footer } from '~/components/footer/Footer'
import { Navbar } from '~/components/navbar/Navbar'
import { cn } from '~/utils/cn'

const roboto = Roboto({
  subsets: ['latin'],
  variable: '--font-roboto',
  weight: ['400', '500', '700'],
})

const robotoSerif = Roboto_Serif({
  subsets: ['latin'],
  variable: '--font-roboto-serif',
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
  style: ['italic', 'normal'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    // We suppress the hydration warning because we're using the ThemeProvider,
    // which causes a mismatch between the server and client render.
    // This is completely fine and applies to the `html` tag only.
    <html lang="en" suppressHydrationWarning>
      <body
        className={cn(roboto.variable, robotoSerif.variable, 'flex flex-col')}
      >
        <ThemeProvider attribute="class">
          <div className="flex flex-col min-h-screen flex-1">
            <Navbar />
            {children}
          </div>
          <Footer />
        </ThemeProvider>
      </body>
    </html>
  )
}
