export { AerodromeClFactoryHandler } from './aerodromeClFactory'
export { AerodromeV2FactoryHandler } from './aerodromeV2Factory'
export { FrankencoinMintinghubHandler } from './frankencoinMintinghub'
export { UniswapV2FactoryHandler } from './uniswapV2Factory'
export { UniswapV3FactoryHandler } from './uniswapV3Factory'
export type { AggregateHandler } from './types'
