// Well-known library / base-contract names that are usually noise when pasting
// a contract into an LLM. They are deselected by default in the copy dialog; the
// user can always re-select them. Matching is by exact declaration name, so this
// list is cheap to extend. Names come mostly from OpenZeppelin, solmate and solady.
export const KNOWN_LIBRARY_NAMES: ReadonlySet<string> = new Set([
  // Access / ownership
  'Ownable',
  'Ownable2Step',
  'OwnableUpgradeable',
  'Owned',
  'Auth',
  'AccessControl',
  'AccessControlUpgradeable',
  'AccessControlEnumerable',
  'IAccessControl',
  // Lifecycle / proxies
  'Initializable',
  'Context',
  'ContextUpgradeable',
  'Pausable',
  'PausableUpgradeable',
  'ReentrancyGuard',
  'ReentrancyGuardUpgradeable',
  'UUPSUpgradeable',
  'Proxy',
  'ERC1967Proxy',
  'ERC1967Upgrade',
  'ERC1967Utils',
  'TransparentUpgradeableProxy',
  'ProxyAdmin',
  'BeaconProxy',
  'UpgradeableBeacon',
  'Clones',
  'Create2',
  'StorageSlot',
  'Multicall',
  'Nonces',
  // Tokens
  'ERC20',
  'ERC20Upgradeable',
  'IERC20',
  'IERC20Metadata',
  'IERC20Permit',
  'ERC20Permit',
  'SafeERC20',
  'ERC721',
  'IERC721',
  'IERC721Receiver',
  'IERC721Metadata',
  'ERC1155',
  'IERC1155',
  'IERC1155Receiver',
  'ERC165',
  'IERC165',
  'SafeTransferLib',
  // Math / utils
  'Math',
  'SafeMath',
  'SignedMath',
  'SafeCast',
  'FixedPointMathLib',
  'FullMath',
  'Address',
  'Strings',
  'LibString',
  'LibBit',
  'Bytes',
  'BytesLib',
  'ECDSA',
  'EIP712',
  'MerkleProof',
  'MerkleProofLib',
  'SignatureChecker',
  'SignatureCheckerLib',
  'Counters',
  'EnumerableSet',
  'EnumerableMap',
  'DoubleEndedQueue',
  'BitMaps',
  'Arrays',
  'Checkpoints',
  'Time',
  'ShortStrings',
  'Panic',
  'Errors',
])
