import type {
  CropAttestation,
  CropAttestationLedger,
  RevokedCropAttestation,
} from '@l2beat/config/build/crops/attestations'
import type { AttestationNetwork } from '@l2beat/config/build/crops/eas'
import { writeFileSync } from 'fs'
import { join } from 'path'

/**
 * The generated data file lives in packages/config so both the CLI and the
 * frontend can read it. Resolved from this file rather than from cwd so the
 * command works from anywhere in the monorepo.
 */
export function getLedgerPath(): string {
  return join(
    __dirname,
    '..',
    '..',
    '..',
    '..',
    'config',
    'src',
    'crops',
    'attestationData.ts',
  )
}

const HEADER = `// Generated by \`l2b crops-attest --execute\`. Do not edit by hand.
//
// A cache of onchain state, not the source of truth: \`l2b crops-verify\` reads
// every uid back from EAS and fails if anything here has drifted. It is
// committed so the API can serve attestation references without an RPC call on
// the request path.
`

export function writeLedger(
  ledgers: Partial<Record<AttestationNetwork, CropAttestationLedger>>,
  path = getLedgerPath(),
): void {
  const body = `${HEADER}export const CROP_ATTESTATION_DATA = ${format(ledgers)}\n`
  writeFileSync(path, body)
}

/**
 * Emitted with sorted keys and a stable field order so a run that changes
 * nothing produces no diff. Biome reformats it on `pnpm format:fix`; this only
 * has to be valid and deterministic.
 */
function format(
  ledgers: Partial<Record<AttestationNetwork, CropAttestationLedger>>,
): string {
  const names = Object.keys(ledgers).sort() as AttestationNetwork[]
  if (names.length === 0) {
    return '{}'
  }
  const entries = names.map((name) => {
    const ledger = ledgers[name]
    if (!ledger) {
      return ''
    }
    return [
      `  ${name}: {`,
      `    network: ${str(ledger.network)} as const,`,
      `    attester: ${str(ledger.attester)},`,
      `    firstBlock: ${ledger.firstBlock},`,
      ...arrayLines('live', byRevision(ledger.live).map(live)),
      ...arrayLines('revoked', byRevision(ledger.revoked).map(revoked)),
      '  },',
    ].join('\n')
  })
  return `{\n${entries.join('\n')}\n}`
}

/** Empty arrays stay on one line, so a first run reads as `revoked: [],`. */
function arrayLines(name: string, entries: string[]): string[] {
  if (entries.length === 0) {
    return [`    ${name}: [],`]
  }
  return [`    ${name}: [`, ...entries, '    ],']
}

/** Oldest revision first, so the file reads as a history. */
function byRevision<T extends { revision: number }>(items: T[]): T[] {
  return [...items].sort((a, b) => a.revision - b.revision)
}

function live(attestation: CropAttestation): string {
  return [
    '      {',
    `        uid: ${str(attestation.uid)},`,
    `        schema: ${str(attestation.schema)},`,
    `        revision: ${attestation.revision},`,
    `        reviewedAt: ${attestation.reviewedAt},`,
    `        projectIds: ${strArray(attestation.projectIds)},`,
    `        txHash: ${str(attestation.txHash)},`,
    `        block: ${attestation.block},`,
    '      },',
  ].join('\n')
}

function revoked(attestation: RevokedCropAttestation): string {
  return [
    '      {',
    `        uid: ${str(attestation.uid)},`,
    `        schema: ${str(attestation.schema)},`,
    `        revision: ${attestation.revision},`,
    `        projectIds: ${strArray(attestation.projectIds)},`,
    `        revokedTxHash: ${str(attestation.revokedTxHash)},`,
    `        revokedBlock: ${attestation.revokedBlock},`,
    '      },',
  ].join('\n')
}

function str(value: string): string {
  return `'${value.replace(/\\/g, '\\\\').replace(/'/g, "\\'")}'`
}

function strArray(values: string[]): string {
  return `[${values.map(str).join(', ')}]`
}
