export const pages = [
  '/scaling/summary',
  '/scaling/risk',
  '/scaling/tvs',
  '/scaling/activity',
  '/scaling/data-availability',
  '/scaling/liveness',
  '/scaling/costs',
  '/scaling/upcoming',
  '/scaling/archived',
  '/bridges/summary',
  '/bridges/archived',
  '/data-availability/summary',
  '/data-availability/risk',
  '/data-availability/throughput',
  '/zk-catalog',
  '/about-us',
  '/donate',
  '/glossary',
  '/faq',
  '/governance',
  '/governance/publications',
  '/governance/publications/governance-review-50',
]

export const projectPages: Record<string, string[]> = {
  scaling: [
    '/scaling/projects/arbitrum',
    '/scaling/projects/base',
    '/scaling/projects/unichain',
    '/scaling/projects/linea',
    '/scaling/projects/fuel',
    '/scaling/projects/zora',
    '/scaling/projects/gasp',
  ],
  bridges: [
    '/bridges/projects/sonicgateway',
    '/bridges/projects/omni',
    '/bridges/projects/connext',
    '/bridges/projects/acrossv3',
    '/bridges/projects/opticsv2',
    '/bridges/projects/transporter',
  ],
  dataAvailability: [
    '/data-availability/projects/ethereum/ethereum',
    '/data-availability/projects/celestia/no-bridge',
    '/data-availability/projects/memo/no-bridge',
    '/data-availability/projects/near/no-bridge',
    '/data-availability/projects/espresso-da/espresso-da',
    '/data-availability/projects/eigen-da/no-bridge',
  ],
  zkCatalog: [
    '/zk-catalog/abstract',
    '/zk-catalog/nebra-upa',
    '/zk-catalog/worldcoin-smtb',
    '/zk-catalog/zeronetwork',
    '/zk-catalog/starknet',
    '/zk-catalog/zksync-era',
    '/zk-catalog/zkcandy',
  ],
  ecosystems: [
    '/ecosystems/arbitrum-orbit',
    '/ecosystems/superchain',
    '/ecosystems/agglayer',
    '/ecosystems/the-elastic-network',
  ],
}
