import type {
  AuditReportRef,
  CollectionRef,
  CollectionsFile,
  ProjectAuditCoverage,
  ReportsFile,
  UnitRecord,
} from '@l2beat/audit-diff'
import { existsSync, readdirSync, readFileSync } from 'fs'
import path from 'path'

/**
 * Where coverage data comes from. The content implementation reads the
 * content-addressed store generated by `@l2beat/audit-diff`; a database-backed
 * implementation can replace it without touching the pages.
 */
export interface AuditCoverageSource {
  listProjects(): ProjectAuditCoverage[]
  getProject(slug: string): ProjectAuditCoverage | undefined
  getUnit(unitHash: string): UnitRecord | undefined
  getReport(id: string): AuditReportRef | undefined
  getCollection(id: string): CollectionRef | undefined
}

const STORE_DIR = path.join(process.cwd(), 'src', 'content', 'audits')

/**
 * Project files are thin and immutable for the process lifetime, so they are
 * read once. Unit records hold sources and diffs and are read on demand.
 */
class ContentAuditCoverageSource implements AuditCoverageSource {
  private projects: ProjectAuditCoverage[] | undefined
  private reports: Record<string, AuditReportRef> | undefined
  private collections: Record<string, CollectionRef> | undefined

  constructor(private readonly dir: string) {}

  listProjects(): ProjectAuditCoverage[] {
    if (!this.projects) {
      const projectsDir = path.join(this.dir, 'projects')
      this.projects = existsSync(projectsDir)
        ? readdirSync(projectsDir)
            .filter((f) => f.endsWith('.json'))
            .map((f) =>
              readJson<ProjectAuditCoverage>(path.join(projectsDir, f)),
            )
            .sort((a, b) => a.slug.localeCompare(b.slug))
        : []
    }
    return this.projects
  }

  getProject(slug: string): ProjectAuditCoverage | undefined {
    return this.listProjects().find((p) => p.slug === slug)
  }

  getUnit(unitHash: string): UnitRecord | undefined {
    if (!/^[0-9a-f]{64}$/.test(unitHash)) return undefined
    const file = path.join(this.dir, 'units', `${unitHash}.json`)
    return existsSync(file) ? readJson<UnitRecord>(file) : undefined
  }

  getReport(id: string): AuditReportRef | undefined {
    if (!this.reports) {
      const file = path.join(this.dir, 'reports.json')
      this.reports = existsSync(file) ? readJson<ReportsFile>(file).reports : {}
    }
    return this.reports[id]
  }

  getCollection(id: string): CollectionRef | undefined {
    if (!this.collections) {
      const file = path.join(this.dir, 'collections.json')
      this.collections = existsSync(file)
        ? readJson<CollectionsFile>(file).collections
        : {}
    }
    return this.collections[id]
  }
}

function readJson<T>(file: string): T {
  return JSON.parse(readFileSync(file, 'utf8')) as T
}

export const auditCoverageSource: AuditCoverageSource =
  new ContentAuditCoverageSource(STORE_DIR)
