import type { ProjectAuditCoverage } from '@l2beat/audit-diff'
import { getCollection } from '~/content/getCollection'

/**
 * Where coverage reports come from. The content implementation reads the JSON
 * files generated by `@l2beat/audit-diff`; a database-backed implementation
 * can replace it without touching the pages.
 */
export interface AuditCoverageSource {
  listProjects(): ProjectAuditCoverage[]
  getProject(slug: string): ProjectAuditCoverage | undefined
}

class ContentAuditCoverageSource implements AuditCoverageSource {
  private cache: ProjectAuditCoverage[] | undefined

  listProjects(): ProjectAuditCoverage[] {
    // The files are a few MB and immutable for the process lifetime.
    this.cache ??= getCollection('audits')
      .map((entry) => entry.data)
      .sort((a, b) => a.slug.localeCompare(b.slug))
    return this.cache
  }

  getProject(slug: string): ProjectAuditCoverage | undefined {
    return this.listProjects().find((p) => p.slug === slug)
  }
}

export const auditCoverageSource: AuditCoverageSource =
  new ContentAuditCoverageSource()
