import { ProjectAuditCoverage } from '@l2beat/audit-diff'
import { defineCollection } from '../defineCollections'

/**
 * Coverage reports generated by `@l2beat/audit-diff`, one JSON file per
 * project. Regenerate with `pnpm --filter @l2beat/audit-diff generate`.
 */
export const auditsCollection = defineCollection({
  type: 'data',
  schema: ProjectAuditCoverage,
})
