/**
 * Precomputed anonymity set data, keyed by project slug. Generated by
 * `packages/config/scripts/computeAnonymitySetCurves.ts` from the privacy-flow
 * CSV exports - the database stores no depositor addresses, so
 * unique-depositor counts cannot be computed at request time.
 *
 * Two views of one metric, both counting unique depositors in a trailing
 * window:
 * - `points`, the window ending at `asOf` with its length on the x axis.
 * - `history`, a window of fixed `historyWindowDays` length whose end slides
 *   along the x axis over the year up to `asOf`.
 */
import curves from './anonymitySetCurves.json'

export interface AnonymitySetCurveBucket {
  id: string
  label: string
  /** Token symbol. Buckets of one token are colored as shades of one hue. */
  family: string
}

/** `[days, ...setSizes]`, one size per bucket, in `buckets` order. */
export type AnonymitySetCurvePoint = number[]

/** `[timestamp, ...setSizes]`, one size per bucket, in `buckets` order. */
export type AnonymitySetHistoryPoint = number[]

export interface AnonymitySetCurves {
  /** Export date of the underlying data, the end of every window. */
  asOf: string
  /** What a single curve counts, which differs per protocol. */
  description: string
  buckets: AnonymitySetCurveBucket[]
  points: AnonymitySetCurvePoint[]
  /** Length of the sliding window `history` is measured over. */
  historyWindowDays: number
  history: AnonymitySetHistoryPoint[]
}

export function getAnonymitySetCurves(
  slug: string,
): AnonymitySetCurves | undefined {
  const project = (
    curves.projects as Record<
      string,
      | {
          description: string
          buckets: AnonymitySetCurveBucket[]
          points: number[][]
          history: number[][]
        }
      | undefined
    >
  )[slug]
  if (!project) return undefined

  return {
    asOf: curves.asOf,
    description: project.description,
    buckets: project.buckets,
    points: project.points,
    historyWindowDays: curves.historyWindowDays,
    history: project.history,
  }
}
