/**
 * Precomputed "anonymity set vs. holding duration" curves, keyed by project
 * slug. Generated by `packages/config/scripts/computeAnonymitySetCurves.ts`
 * from the privacy-flow CSV exports - the database stores no depositor
 * addresses, so unique-depositor counts cannot be computed at request time.
 *
 * The value at `days` is the number of unique addresses that deposited into a
 * bucket in the `days` long window ending at `asOf`.
 */
import curves from './anonymitySetCurves.json'

export interface AnonymitySetCurveBucket {
  id: string
  label: string
}

/** `[days, ...setSizes]`, one size per bucket, in `buckets` order. */
export type AnonymitySetCurvePoint = number[]

export interface AnonymitySetCurves {
  /** Export date of the underlying data, the end of every window. */
  asOf: string
  /** What a single curve counts, which differs per protocol. */
  description: string
  buckets: AnonymitySetCurveBucket[]
  points: AnonymitySetCurvePoint[]
}

export function getAnonymitySetCurves(
  slug: string,
): AnonymitySetCurves | undefined {
  const project = (
    curves.projects as Record<
      string,
      | {
          description: string
          buckets: AnonymitySetCurveBucket[]
          points: number[][]
        }
      | undefined
    >
  )[slug]
  if (!project) return undefined

  return {
    asOf: curves.asOf,
    description: project.description,
    buckets: project.buckets,
    points: project.points,
  }
}
