import { ChainSpecificAddress, formatJson } from '@l2beat/shared-pure'
import { readFileSync, writeFileSync } from 'fs'
import { merge, mergeWith, uniqBy } from 'lodash'

const ignoredFiles: Set<string> = new Set([
  'src/projects/kroma/config.jsonc', // DONE
  'src/projects/hyperliquid/config.jsonc', // DONE
  'src/projects/optimism/config.jsonc', // DONE
  'src/projects/lisk/config.jsonc', // DONE
  'src/projects/omni/config.jsonc', // DONE
  'src/projects/amarok/config.jsonc', // DONE
  'src/projects/fuel/config.jsonc', // DONE
  'src/projects/eclipse/config.jsonc', // DONE
  'src/projects/scroll/config.jsonc', // DONE
  'src/projects/across-v3/config.jsonc', // DONE
  'src/projects/shared-zk-stack/config.jsonc',
  'src/projects/socket/config.jsonc', // DONE
  'src/projects/plumenetwork/config.jsonc', // DONE
  'src/projects/base/config.jsonc', // DONE
  'src/projects/fuelv1/config.jsonc', // DONE
  'src/projects/hemi/config.jsonc', // DONE
  'src/projects/kinto/config.jsonc', // DONE
  'src/projects/hyperlane/config.jsonc', // DONE
  'src/projects/tokens/config.jsonc', // DONE
  'src/projects/katana/config.jsonc', // DONE
  'src/projects/taiko/config.jsonc', // DONE
  'src/projects/starknet/config.jsonc', // DONE
  'src/projects/unichain/config.jsonc', // DONE
  'src/projects/penchain/config.jsonc',
])

const fileList = [
  'src/projects/abstract/config.jsonc',
  'src/projects/across-v3/config.jsonc',
  'src/projects/aevo/config.jsonc',
  'src/projects/agglayer/config.jsonc',
  'src/projects/aiechain/config.jsonc',
  'src/projects/airas/config.jsonc',
  'src/projects/alephzero/config.jsonc',
  'src/projects/alienx/config.jsonc',
  'src/projects/align/config.jsonc',
  'src/projects/allbridge/config.jsonc',
  'src/projects/allo/config.jsonc',
  'src/projects/alphadune/config.jsonc',
  'src/projects/amarok/config.jsonc',
  'src/projects/ancient/config.jsonc',
  'src/projects/animechain/config.jsonc',
  'src/projects/ankr/config.jsonc',
  'src/projects/anomaly/config.jsonc',
  'src/projects/apechain/config.jsonc',
  'src/projects/apex/config.jsonc',
  'src/projects/appchain/config.jsonc',
  'src/projects/aptos/config.jsonc',
  'src/projects/arbitrum-orbit/config.jsonc',
  'src/projects/arbitrum/config.jsonc',
  'src/projects/arcology/config.jsonc',
  'src/projects/arenaz/config.jsonc',
  'src/projects/arithmic/config.jsonc',
  'src/projects/astarzkevm/config.jsonc',
  'src/projects/automata/config.jsonc',
  'src/projects/avail/config.jsonc',
  'src/projects/avalanche/config.jsonc',
  'src/projects/aviveworld/config.jsonc',
  'src/projects/axonum/config.jsonc',
  'src/projects/azchain/config.jsonc',
  'src/projects/aztec-v2/config.jsonc',
  'src/projects/aztec/config.jsonc',
  'src/projects/aztecconnect/config.jsonc',
  'src/projects/b3/config.jsonc',
  'src/projects/base/config.jsonc',
  'src/projects/beamer-bridge-v2/config.jsonc',
  'src/projects/bitlazer/config.jsonc',
  'src/projects/blast/config.jsonc',
  'src/projects/blessnet/config.jsonc',
  'src/projects/blobstream/config.jsonc',
  'src/projects/blockfit/config.jsonc',
  'src/projects/bob/config.jsonc',
  'src/projects/bobanetwork/config.jsonc',
  'src/projects/brine/config.jsonc',
  'src/projects/bsc/config.jsonc',
  'src/projects/bugbuster/config.jsonc',
  'src/projects/camp/config.jsonc',
  'src/projects/canto/config.jsonc',
  'src/projects/canvasconnect/config.jsonc',
  'src/projects/capx/config.jsonc',
  'src/projects/cartesi-prt-honeypot/config.jsonc',
  'src/projects/cbridge/config.jsonc',
  'src/projects/celestia/config.jsonc',
  'src/projects/celo/config.jsonc',
  'src/projects/chainport/config.jsonc',
  'src/projects/cheese/config.jsonc',
  'src/projects/clique/config.jsonc',
  'src/projects/connext/config.jsonc',
  'src/projects/conwai/config.jsonc',
  'src/projects/corn/config.jsonc',
  'src/projects/coti/config.jsonc',
  'src/projects/creator/config.jsonc',
  'src/projects/creatorchain/config.jsonc',
  'src/projects/cronoszkevm/config.jsonc',
  'src/projects/cyber/config.jsonc',
  'src/projects/datalake/config.jsonc',
  'src/projects/davos/config.jsonc',
  'src/projects/dbk/config.jsonc',
  'src/projects/dcamonster/config.jsonc',
  'src/projects/debridge/config.jsonc',
  'src/projects/degate/config.jsonc',
  'src/projects/degate2/config.jsonc',
  'src/projects/degate3/config.jsonc',
  'src/projects/degen/config.jsonc',
  'src/projects/deri/config.jsonc',
  'src/projects/destra/config.jsonc',
  'src/projects/deversifi/config.jsonc',
  'src/projects/dodochain/config.jsonc',
  'src/projects/donatuz/config.jsonc',
  'src/projects/dydx/config.jsonc',
  'src/projects/ebichain/config.jsonc',
  'src/projects/eclipse/config.jsonc',
  'src/projects/edgeless/config.jsonc',
  'src/projects/educhain/config.jsonc',
  'src/projects/eigenda/config.jsonc',
  'src/projects/espresso/config.jsonc',
  'src/projects/ethereum/config.jsonc',
  'src/projects/ethernity/config.jsonc',
  'src/projects/evedex/config.jsonc',
  'src/projects/everclear/config.jsonc',
  'src/projects/everclearbridge/config.jsonc',
  'src/projects/facet/config.jsonc',
  'src/projects/fhenix/config.jsonc',
  'src/projects/fiefdom/config.jsonc',
  'src/projects/fluence/config.jsonc',
  'src/projects/fluent/config.jsonc',
  'src/projects/form/config.jsonc',
  'src/projects/forta/config.jsonc',
  'src/projects/fraxferry/config.jsonc',
  'src/projects/fraxtal/config.jsonc',
  'src/projects/fuel/config.jsonc',
  'src/projects/fuelv1/config.jsonc',
  'src/projects/funki/config.jsonc',
  'src/projects/fuse/config.jsonc',
  'src/projects/galxegravity/config.jsonc',
  'src/projects/game7/config.jsonc',
  'src/projects/gameswift/config.jsonc',
  'src/projects/gasp/config.jsonc',
  'src/projects/gateway/config.jsonc',
  'src/projects/geist/config.jsonc',
  'src/projects/genlayer/config.jsonc',
  'src/projects/gluon/config.jsonc',
  'src/projects/gmnetwork/config.jsonc',
  'src/projects/gnosis/config.jsonc',
  'src/projects/gpt/config.jsonc',
  'src/projects/gravity/config.jsonc',
  'src/projects/gridy/config.jsonc',
  'src/projects/grvt/config.jsonc',
  'src/projects/gwyneth/config.jsonc',
  'src/projects/ham/config.jsonc',
  'src/projects/happychain/config.jsonc',
  'src/projects/hashkey/config.jsonc',
  'src/projects/haust/config.jsonc',
  'src/projects/hemi/config.jsonc',
  'src/projects/henez/config.jsonc',
  'src/projects/hermez/config.jsonc',
  'src/projects/hibachi/config.jsonc',
  'src/projects/honeypot/config.jsonc',
  'src/projects/hook/config.jsonc',
  'src/projects/hop/config.jsonc',
  'src/projects/huddle01/config.jsonc',
  'src/projects/hybrid/config.jsonc',
  'src/projects/hychain/config.jsonc',
  'src/projects/hyperagi/config.jsonc',
  'src/projects/hyperlane/config.jsonc',
  'src/projects/hyperliquid/config.jsonc',
  'src/projects/hyphen/config.jsonc',
  'src/projects/hypr/config.jsonc',
  'src/projects/immutablex/config.jsonc',
  'src/projects/immutablezkevm/config.jsonc',
  'src/projects/inevm/config.jsonc',
  'src/projects/ink/config.jsonc',
  'src/projects/intmax/config.jsonc',
  'src/projects/karak/config.jsonc',
  'src/projects/katana/config.jsonc',
  'src/projects/kinto/config.jsonc',
  'src/projects/koi/config.jsonc',
  'src/projects/kontos/config.jsonc',
  'src/projects/kroma/config.jsonc',
  'src/projects/l3x/config.jsonc',
  'src/projects/lachain/config.jsonc',
  'src/projects/lambda/config.jsonc',
  'src/projects/lasernet/config.jsonc',
  'src/projects/layer2finance/config.jsonc',
  'src/projects/layer2financezk/config.jsonc',
  'src/projects/layerai/config.jsonc',
  'src/projects/layerzerov2oft/config.jsonc',
  'src/projects/leaf/config.jsonc',
  'src/projects/lens/config.jsonc',
  'src/projects/liftchain/config.jsonc',
  'src/projects/lightlink/config.jsonc',
  'src/projects/linea/config.jsonc',
  'src/projects/lisk/config.jsonc',
  'src/projects/loopring/config.jsonc',
  'src/projects/lootchain/config.jsonc',
  'src/projects/lumia/config.jsonc',
  'src/projects/lumiterra/config.jsonc',
  'src/projects/lyra/config.jsonc',
  'src/projects/lzomnichain/config.jsonc',
  'src/projects/mantapacific/config.jsonc',
  'src/projects/mantle/config.jsonc',
  'src/projects/mawari/config.jsonc',
  'src/projects/memento/config.jsonc',
  'src/projects/memo/config.jsonc',
  'src/projects/metal/config.jsonc',
  'src/projects/metis/config.jsonc',
  'src/projects/millicent/config.jsonc',
  'src/projects/mindchain/config.jsonc',
  'src/projects/mint/config.jsonc',
  'src/projects/mode/config.jsonc',
  'src/projects/molten/config.jsonc',
  'src/projects/moonchain/config.jsonc',
  'src/projects/moonveil/config.jsonc',
  'src/projects/morph/config.jsonc',
  'src/projects/move/config.jsonc',
  'src/projects/multichain/config.jsonc',
  'src/projects/muster/config.jsonc',
  'src/projects/mvchain/config.jsonc',
  'src/projects/myria/config.jsonc',
  'src/projects/myshell/config.jsonc',
  'src/projects/nal/config.jsonc',
  'src/projects/near/config.jsonc',
  'src/projects/nearomni/config.jsonc',
  'src/projects/nebraupa/config.jsonc',
  'src/projects/network3/config.jsonc',
  'src/projects/neva/config.jsonc',
  'src/projects/nil/config.jsonc',
  'src/projects/nodle/config.jsonc',
  'src/projects/nomad/config.jsonc',
  'src/projects/nova/config.jsonc',
  'src/projects/nums/config.jsonc',
  'src/projects/oevnetwork/config.jsonc',
  'src/projects/ola/config.jsonc',
  'src/projects/omgnetwork/config.jsonc',
  'src/projects/omni/config.jsonc',
  'src/projects/onchain/config.jsonc',
  'src/projects/onyx/config.jsonc',
  'src/projects/opcm16/config.jsonc',
  'src/projects/openzk/config.jsonc',
  'src/projects/opticsV1/config.jsonc',
  'src/projects/opticsV2/config.jsonc',
  'src/projects/optimism/config.jsonc',
  'src/projects/optopia/config.jsonc',
  'src/projects/orbit/config.jsonc',
  'src/projects/orbiter/config.jsonc',
  'src/projects/orderly/config.jsonc',
  'src/projects/oursong/config.jsonc',
  'src/projects/ozean/config.jsonc',
  'src/projects/pandasea/config.jsonc',
  'src/projects/paradex/config.jsonc',
  'src/projects/parallel/config.jsonc',
  'src/projects/patex/config.jsonc',
  'src/projects/pay/config.jsonc',
  'src/projects/payy/config.jsonc',
  'src/projects/penchain/config.jsonc',
  'src/projects/pepeunchained/config.jsonc',
  'src/projects/pepeunchained2/config.jsonc',
  'src/projects/phala/config.jsonc',
  'src/projects/playblock/config.jsonc',
  'src/projects/plumenetwork/config.jsonc',
  'src/projects/pmon/config.jsonc',
  'src/projects/pNetwork/config.jsonc',
  'src/projects/polygon-pos/config.jsonc',
  'src/projects/polygonmiden/config.jsonc',
  'src/projects/polygonpos2/config.jsonc',
  'src/projects/polygonzkevm/config.jsonc',
  'src/projects/polynetwork/config.jsonc',
  'src/projects/polynomial/config.jsonc',
  'src/projects/popapex/config.jsonc',
  'src/projects/popboss/config.jsonc',
  'src/projects/portal/config.jsonc',
  'src/projects/powerloom/config.jsonc',
  'src/projects/prom/config.jsonc',
  'src/projects/publicgoodsnetwork/config.jsonc',
  'src/projects/puffer/config.jsonc',
  'src/projects/pulseChain/config.jsonc',
  'src/projects/quarkchain/config.jsonc',
  'src/projects/r0ar/config.jsonc',
  'src/projects/race/config.jsonc',
  'src/projects/rari/config.jsonc',
  'src/projects/rarimo/config.jsonc',
  'src/projects/real/config.jsonc',
  'src/projects/reddioex/config.jsonc',
  'src/projects/reddiozkvm/config.jsonc',
  'src/projects/redstone/config.jsonc',
  'src/projects/reya/config.jsonc',
  'src/projects/risczero/config.jsonc',
  'src/projects/rise/config.jsonc',
  'src/projects/rivalz/config.jsonc',
  'src/projects/river/config.jsonc',
  'src/projects/ronin/config.jsonc',
  'src/projects/rss3/config.jsonc',
  'src/projects/rufus/config.jsonc',
  'src/projects/sanko/config.jsonc',
  'src/projects/satellite/config.jsonc',
  'src/projects/scroll/config.jsonc',
  'src/projects/settlus/config.jsonc',
  'src/projects/shape/config.jsonc',
  'src/projects/shared-eigenlayer/config.jsonc',
  'src/projects/shared-polygon-cdk/config.jsonc',
  'src/projects/shared-sharp-verifier/config.jsonc',
  'src/projects/shared-sp1/config.jsonc',
  'src/projects/shared-zk-stack/config.jsonc',
  'src/projects/shibarium/config.jsonc',
  'src/projects/silicon/config.jsonc',
  'src/projects/singularityfinance/config.jsonc',
  'src/projects/skale-ima/config.jsonc',
  'src/projects/skatechain/config.jsonc',
  'src/projects/skynet/config.jsonc',
  'src/projects/slingshot/config.jsonc',
  'src/projects/snaxchain/config.jsonc',
  'src/projects/socket/config.jsonc',
  'src/projects/sollet/config.jsonc',
  'src/projects/solo/config.jsonc',
  'src/projects/soneium/config.jsonc',
  'src/projects/sonicgateway/config.jsonc',
  'src/projects/soon/config.jsonc',
  'src/projects/sophon/config.jsonc',
  'src/projects/sorare/config.jsonc',
  'src/projects/soulwallet/config.jsonc',
  'src/projects/sovrun/config.jsonc',
  'src/projects/sp1blobstream/config.jsonc',
  'src/projects/sp1vector/config.jsonc',
  'src/projects/spheron/config.jsonc',
  'src/projects/spire/config.jsonc',
  'src/projects/stack/config.jsonc',
  'src/projects/stargate/config.jsonc',
  'src/projects/stargatev2/config.jsonc',
  'src/projects/starknet/config.jsonc',
  'src/projects/status/config.jsonc',
  'src/projects/studiochain/config.jsonc',
  'src/projects/superchain/config.jsonc',
  'src/projects/superlumio/config.jsonc',
  'src/projects/superposition/config.jsonc',
  'src/projects/superseed/config.jsonc',
  'src/projects/surge/config.jsonc',
  'src/projects/swan/config.jsonc',
  'src/projects/swell/config.jsonc',
  'src/projects/sxnetwork/config.jsonc',
  'src/projects/sxt/config.jsonc',
  'src/projects/sygma/config.jsonc',
  'src/projects/symbiosis/config.jsonc',
  'src/projects/synapse/config.jsonc',
  'src/projects/syndicateframe/config.jsonc',
  'src/projects/syndr/config.jsonc',
  'src/projects/t1/config.jsonc',
  'src/projects/taiko/config.jsonc',
  'src/projects/tea/config.jsonc',
  'src/projects/telos/config.jsonc',
  'src/projects/ten/config.jsonc',
  'src/projects/termstructure/config.jsonc',
  'src/projects/ternoa/config.jsonc',
  'src/projects/thanos/config.jsonc',
  'src/projects/the-elastic-network/config.jsonc',
  'src/projects/thebinaryholdings/config.jsonc',
  'src/projects/tokens/config.jsonc',
  'src/projects/train/config.jsonc',
  'src/projects/transporter/config.jsonc',
  'src/projects/treasure/config.jsonc',
  'src/projects/tusima/config.jsonc',
  'src/projects/ungaii/config.jsonc',
  'src/projects/unichain/config.jsonc',
  'src/projects/union/config.jsonc',
  'src/projects/unite/config.jsonc',
  'src/projects/vector/config.jsonc',
  'src/projects/vessel/config.jsonc',
  'src/projects/winr/config.jsonc',
  'src/projects/wirex/config.jsonc',
  'src/projects/witness/config.jsonc',
  'src/projects/wonder/config.jsonc',
  'src/projects/worldchain/config.jsonc',
  'src/projects/worldcoin/config.jsonc',
  'src/projects/worldcoinsemaphore/config.jsonc',
  'src/projects/worldcoinsmtb/config.jsonc',
  'src/projects/wormholeV1/config.jsonc',
  'src/projects/xai/config.jsonc',
  'src/projects/xchain/config.jsonc',
  'src/projects/xlayer/config.jsonc',
  'src/projects/xpla/config.jsonc',
  'src/projects/xrone/config.jsonc',
  'src/projects/xsolla/config.jsonc',
  'src/projects/xterio/config.jsonc',
  'src/projects/yellowstone/config.jsonc',
  'src/projects/zentachain/config.jsonc',
  'src/projects/zeronetwork/config.jsonc',
  'src/projects/zircuit/config.jsonc',
  'src/projects/zkcandy/config.jsonc',
  'src/projects/zkfair/config.jsonc',
  'src/projects/zklighter/config.jsonc',
  'src/projects/zklinknova/config.jsonc',
  'src/projects/zkspace/config.jsonc',
  'src/projects/zkswap/config.jsonc',
  'src/projects/zkswap2/config.jsonc',
  'src/projects/zksync/config.jsonc',
  'src/projects/zksync2/config.jsonc',
  'src/projects/zora/config.jsonc',
]

for (const file of fileList) {
  if (ignoredFiles.has(file)) {
    continue
  }

  const content = readFileSync(file, 'utf-8')
  const parsed = JSON.parse(content)

  const result = structuredClone(parsed)
  // biome-ignore lint/performance/noDelete: we know
  delete result.chains

  const chains = Object.keys(parsed.chains)
  let final: unknown = {}
  for (const chain of chains) {
    const data = prefixAddresses(chain, parsed.chains[chain])
    final = mergeWith(final, data, (a, b) => {
      if (Array.isArray(a) && Array.isArray(b)) {
        return uniqBy(a.concat(b), (x) => JSON.stringify(x))
      }
    })
  }

  writeFileSync(file, formatJson(merge(result, final)))
}

// TODO(radomski): We need to test this
function prefixAddresses(longChain: string, value: unknown): unknown {
  if (Array.isArray(value)) {
    return value.map((v) => prefixAddresses(longChain, v))
  }

  if (typeof value === 'object' && value !== null) {
    return Object.fromEntries(
      Object.entries(value).map(([key, value]) => [
        prefixAddresses(longChain, key),
        prefixAddresses(longChain, value as unknown),
      ]),
    )
  }

  if (typeof value === 'string') {
    try {
      return ChainSpecificAddress.fromLong(longChain, value).toString()
    } catch {
      return value
    }
  }

  return value
}
