node -r esbuild-register ../discovery/src/cli.ts discover ethereum shared-eigenlayer --dev
node -r esbuild-register ../discovery/src/cli.ts discover ethereum shared-polygon-cdk --dev
node -r esbuild-register ../discovery/src/cli.ts discover ethereum shared-sharp-verifier --dev
node -r esbuild-register ../discovery/src/cli.ts discover ethereum shared-zk-stack --dev
node -r esbuild-register ../discovery/src/cli.ts discover ethereum abstract --dev
node -r esbuild-register ../discovery/src/cli.ts discover ethereum across-v3 --dev
node -r esbuild-register ../discovery/src/cli.ts discover ethereum aevo --dev
node -r esbuild-register ../discovery/src/cli.ts discover ethereum alephzero --dev
node -r esbuild-register ../discovery/src/cli.ts discover ethereum alienx --dev
node -r esbuild-register ../discovery/src/cli.ts discover ethereum allbridge --dev
node -r esbuild-register ../discovery/src/cli.ts discover ethereum amarok --dev
node -r esbuild-register ../discovery/src/cli.ts discover ethereum ancient --dev
node -r esbuild-register ../discovery/src/cli.ts discover ethereum apex --dev
node -r esbuild-register ../discovery/src/cli.ts discover ethereum aptos --dev
node -r esbuild-register ../discovery/src/cli.ts discover ethereum arbitrum --dev
node -r esbuild-register ../discovery/src/cli.ts discover ethereum arenaz --dev
node -r esbuild-register ../discovery/src/cli.ts discover ethereum astarzkevm --dev
node -r esbuild-register ../discovery/src/cli.ts discover ethereum automata --dev
node -r esbuild-register ../discovery/src/cli.ts discover ethereum avalanche --dev
node -r esbuild-register ../discovery/src/cli.ts discover ethereum aztec --dev
node -r esbuild-register ../discovery/src/cli.ts discover ethereum aztecconnect --dev
node -r esbuild-register ../discovery/src/cli.ts discover ethereum base --dev
node -r esbuild-register ../discovery/src/cli.ts discover ethereum beamer-bridge-v2 --dev
node -r esbuild-register ../discovery/src/cli.ts discover ethereum blast --dev
node -r esbuild-register ../discovery/src/cli.ts discover ethereum blobstream --dev
node -r esbuild-register ../discovery/src/cli.ts discover ethereum bob --dev
node -r esbuild-register ../discovery/src/cli.ts discover ethereum bobanetwork --dev
node -r esbuild-register ../discovery/src/cli.ts discover ethereum brine --dev
node -r esbuild-register ../discovery/src/cli.ts discover ethereum canvasconnect --dev
node -r esbuild-register ../discovery/src/cli.ts discover ethereum cbridge --dev
node -r esbuild-register ../discovery/src/cli.ts discover ethereum chainport --dev
node -r esbuild-register ../discovery/src/cli.ts discover ethereum connext --dev
node -r esbuild-register ../discovery/src/cli.ts discover ethereum corn --dev
node -r esbuild-register ../discovery/src/cli.ts discover ethereum cronoszkevm --dev
node -r esbuild-register ../discovery/src/cli.ts discover ethereum cyber --dev
node -r esbuild-register ../discovery/src/cli.ts discover ethereum dbk --dev
node -r esbuild-register ../discovery/src/cli.ts discover ethereum debridge --dev
node -r esbuild-register ../discovery/src/cli.ts discover ethereum degate --dev
node -r esbuild-register ../discovery/src/cli.ts discover ethereum degate2 --dev
node -r esbuild-register ../discovery/src/cli.ts discover ethereum degate3 --dev
node -r esbuild-register ../discovery/src/cli.ts discover ethereum deversifi --dev
node -r esbuild-register ../discovery/src/cli.ts discover ethereum dydx --dev
node -r esbuild-register ../discovery/src/cli.ts discover ethereum ebichain --dev
node -r esbuild-register ../discovery/src/cli.ts discover ethereum eclipse --dev
node -r esbuild-register ../discovery/src/cli.ts discover ethereum edgeless --dev
node -r esbuild-register ../discovery/src/cli.ts discover ethereum eigenda --dev
node -r esbuild-register ../discovery/src/cli.ts discover ethereum espresso --dev
node -r esbuild-register ../discovery/src/cli.ts discover ethereum ethernity --dev
node -r esbuild-register ../discovery/src/cli.ts discover ethereum everclear --dev
node -r esbuild-register ../discovery/src/cli.ts discover ethereum facet --dev
node -r esbuild-register ../discovery/src/cli.ts discover ethereum fluence --dev
node -r esbuild-register ../discovery/src/cli.ts discover ethereum form --dev
node -r esbuild-register ../discovery/src/cli.ts discover ethereum fraxferry --dev
node -r esbuild-register ../discovery/src/cli.ts discover ethereum fraxtal --dev
node -r esbuild-register ../discovery/src/cli.ts discover ethereum fuel --dev
node -r esbuild-register ../discovery/src/cli.ts discover ethereum fuelv1 --dev
node -r esbuild-register ../discovery/src/cli.ts discover ethereum galxegravity --dev
node -r esbuild-register ../discovery/src/cli.ts discover ethereum gluon --dev
node -r esbuild-register ../discovery/src/cli.ts discover ethereum gmnetwork --dev
node -r esbuild-register ../discovery/src/cli.ts discover ethereum gpt --dev
node -r esbuild-register ../discovery/src/cli.ts discover ethereum gravity --dev
node -r esbuild-register ../discovery/src/cli.ts discover ethereum grvt --dev
node -r esbuild-register ../discovery/src/cli.ts discover ethereum hashkey --dev
node -r esbuild-register ../discovery/src/cli.ts discover ethereum hermez --dev
node -r esbuild-register ../discovery/src/cli.ts discover ethereum honeypot --dev
node -r esbuild-register ../discovery/src/cli.ts discover ethereum hop --dev
node -r esbuild-register ../discovery/src/cli.ts discover ethereum hychain --dev
node -r esbuild-register ../discovery/src/cli.ts discover ethereum hyperlane --dev
node -r esbuild-register ../discovery/src/cli.ts discover ethereum hyphen --dev
node -r esbuild-register ../discovery/src/cli.ts discover ethereum hypr --dev
node -r esbuild-register ../discovery/src/cli.ts discover ethereum immutablex --dev
node -r esbuild-register ../discovery/src/cli.ts discover ethereum immutablezkevm --dev
node -r esbuild-register ../discovery/src/cli.ts discover ethereum ink --dev
node -r esbuild-register ../discovery/src/cli.ts discover ethereum karak --dev
node -r esbuild-register ../discovery/src/cli.ts discover ethereum kinto --dev
node -r esbuild-register ../discovery/src/cli.ts discover ethereum kroma --dev
node -r esbuild-register ../discovery/src/cli.ts discover ethereum lambda --dev
node -r esbuild-register ../discovery/src/cli.ts discover ethereum layer2finance --dev
node -r esbuild-register ../discovery/src/cli.ts discover ethereum layer2financezk --dev
node -r esbuild-register ../discovery/src/cli.ts discover ethereum layerzerov2oft --dev
node -r esbuild-register ../discovery/src/cli.ts discover ethereum lightlink --dev
node -r esbuild-register ../discovery/src/cli.ts discover ethereum linea --dev
node -r esbuild-register ../discovery/src/cli.ts discover ethereum lisk --dev
node -r esbuild-register ../discovery/src/cli.ts discover ethereum loopring --dev
node -r esbuild-register ../discovery/src/cli.ts discover ethereum lumia --dev
node -r esbuild-register ../discovery/src/cli.ts discover ethereum lyra --dev
node -r esbuild-register ../discovery/src/cli.ts discover ethereum lzomnichain --dev
node -r esbuild-register ../discovery/src/cli.ts discover ethereum mantapacific --dev
node -r esbuild-register ../discovery/src/cli.ts discover ethereum mantle --dev
node -r esbuild-register ../discovery/src/cli.ts discover ethereum metal --dev
node -r esbuild-register ../discovery/src/cli.ts discover ethereum metis --dev
node -r esbuild-register ../discovery/src/cli.ts discover ethereum mint --dev
node -r esbuild-register ../discovery/src/cli.ts discover ethereum mode --dev
node -r esbuild-register ../discovery/src/cli.ts discover ethereum morph --dev
node -r esbuild-register ../discovery/src/cli.ts discover ethereum multichain --dev
node -r esbuild-register ../discovery/src/cli.ts discover ethereum myria --dev
node -r esbuild-register ../discovery/src/cli.ts discover ethereum near --dev
node -r esbuild-register ../discovery/src/cli.ts discover ethereum nebraupa --dev
node -r esbuild-register ../discovery/src/cli.ts discover ethereum nomad --dev
node -r esbuild-register ../discovery/src/cli.ts discover ethereum nova --dev
node -r esbuild-register ../discovery/src/cli.ts discover ethereum oevnetwork --dev
node -r esbuild-register ../discovery/src/cli.ts discover ethereum omgnetwork --dev
node -r esbuild-register ../discovery/src/cli.ts discover ethereum omni --dev
node -r esbuild-register ../discovery/src/cli.ts discover ethereum opticsV1 --dev
node -r esbuild-register ../discovery/src/cli.ts discover ethereum opticsV2 --dev
node -r esbuild-register ../discovery/src/cli.ts discover ethereum optimism --dev
node -r esbuild-register ../discovery/src/cli.ts discover ethereum optopia --dev
node -r esbuild-register ../discovery/src/cli.ts discover ethereum orbit --dev
node -r esbuild-register ../discovery/src/cli.ts discover ethereum orbiter --dev
node -r esbuild-register ../discovery/src/cli.ts discover ethereum orderly --dev
node -r esbuild-register ../discovery/src/cli.ts discover ethereum pNetwork --dev
node -r esbuild-register ../discovery/src/cli.ts discover ethereum paradex --dev
node -r esbuild-register ../discovery/src/cli.ts discover ethereum parallel --dev
node -r esbuild-register ../discovery/src/cli.ts discover ethereum pepeunchained --dev
node -r esbuild-register ../discovery/src/cli.ts discover ethereum phala --dev
node -r esbuild-register ../discovery/src/cli.ts discover ethereum polygon-pos --dev
node -r esbuild-register ../discovery/src/cli.ts discover ethereum polygonzkevm --dev
node -r esbuild-register ../discovery/src/cli.ts discover ethereum polynetwork --dev
node -r esbuild-register ../discovery/src/cli.ts discover ethereum polynomial --dev
node -r esbuild-register ../discovery/src/cli.ts discover ethereum portal --dev
node -r esbuild-register ../discovery/src/cli.ts discover ethereum publicgoodsnetwork --dev
node -r esbuild-register ../discovery/src/cli.ts discover ethereum pulseChain --dev
node -r esbuild-register ../discovery/src/cli.ts discover ethereum race --dev
node -r esbuild-register ../discovery/src/cli.ts discover ethereum real --dev
node -r esbuild-register ../discovery/src/cli.ts discover ethereum reddioex --dev
node -r esbuild-register ../discovery/src/cli.ts discover ethereum redstone --dev
node -r esbuild-register ../discovery/src/cli.ts discover ethereum reya --dev
node -r esbuild-register ../discovery/src/cli.ts discover ethereum river --dev
node -r esbuild-register ../discovery/src/cli.ts discover ethereum ronin --dev
node -r esbuild-register ../discovery/src/cli.ts discover ethereum rss3 --dev
node -r esbuild-register ../discovery/src/cli.ts discover ethereum satellite --dev
node -r esbuild-register ../discovery/src/cli.ts discover ethereum scroll --dev
node -r esbuild-register ../discovery/src/cli.ts discover ethereum shape --dev
node -r esbuild-register ../discovery/src/cli.ts discover ethereum silicon --dev
node -r esbuild-register ../discovery/src/cli.ts discover ethereum skale-ima --dev
node -r esbuild-register ../discovery/src/cli.ts discover ethereum socket --dev
node -r esbuild-register ../discovery/src/cli.ts discover ethereum sollet --dev
node -r esbuild-register ../discovery/src/cli.ts discover ethereum soneium --dev
node -r esbuild-register ../discovery/src/cli.ts discover ethereum sonicgateway --dev
node -r esbuild-register ../discovery/src/cli.ts discover ethereum soon --dev
node -r esbuild-register ../discovery/src/cli.ts discover ethereum sophon --dev
node -r esbuild-register ../discovery/src/cli.ts discover ethereum sorare --dev
node -r esbuild-register ../discovery/src/cli.ts discover ethereum stargate --dev
node -r esbuild-register ../discovery/src/cli.ts discover ethereum stargatev2 --dev
node -r esbuild-register ../discovery/src/cli.ts discover ethereum starknet --dev
node -r esbuild-register ../discovery/src/cli.ts discover ethereum superlumio --dev
node -r esbuild-register ../discovery/src/cli.ts discover ethereum swan --dev
node -r esbuild-register ../discovery/src/cli.ts discover ethereum swell --dev
node -r esbuild-register ../discovery/src/cli.ts discover ethereum sxnetwork --dev
node -r esbuild-register ../discovery/src/cli.ts discover ethereum sygma --dev
node -r esbuild-register ../discovery/src/cli.ts discover ethereum symbiosis --dev
node -r esbuild-register ../discovery/src/cli.ts discover ethereum synapse --dev
node -r esbuild-register ../discovery/src/cli.ts discover ethereum taiko --dev
node -r esbuild-register ../discovery/src/cli.ts discover ethereum termstructure --dev
node -r esbuild-register ../discovery/src/cli.ts discover ethereum ternoa --dev
node -r esbuild-register ../discovery/src/cli.ts discover ethereum thebinaryholdings --dev
node -r esbuild-register ../discovery/src/cli.ts discover ethereum tokens --dev
node -r esbuild-register ../discovery/src/cli.ts discover ethereum transporter --dev
node -r esbuild-register ../discovery/src/cli.ts discover ethereum treasure --dev
node -r esbuild-register ../discovery/src/cli.ts discover ethereum unichain --dev
node -r esbuild-register ../discovery/src/cli.ts discover ethereum vector --dev
node -r esbuild-register ../discovery/src/cli.ts discover ethereum wirex --dev
node -r esbuild-register ../discovery/src/cli.ts discover ethereum witness --dev
node -r esbuild-register ../discovery/src/cli.ts discover ethereum worldchain --dev
node -r esbuild-register ../discovery/src/cli.ts discover ethereum worldcoin --dev
node -r esbuild-register ../discovery/src/cli.ts discover ethereum xchain --dev
node -r esbuild-register ../discovery/src/cli.ts discover ethereum xdai --dev
node -r esbuild-register ../discovery/src/cli.ts discover ethereum xlayer --dev
node -r esbuild-register ../discovery/src/cli.ts discover ethereum xterio --dev
node -r esbuild-register ../discovery/src/cli.ts discover ethereum zeronetwork --dev
node -r esbuild-register ../discovery/src/cli.ts discover ethereum zircuit --dev
node -r esbuild-register ../discovery/src/cli.ts discover ethereum zkfair --dev
node -r esbuild-register ../discovery/src/cli.ts discover ethereum zklinknova --dev
node -r esbuild-register ../discovery/src/cli.ts discover ethereum zkspace --dev
node -r esbuild-register ../discovery/src/cli.ts discover ethereum zkswap --dev
node -r esbuild-register ../discovery/src/cli.ts discover ethereum zkswap2 --dev
node -r esbuild-register ../discovery/src/cli.ts discover ethereum zksync --dev
node -r esbuild-register ../discovery/src/cli.ts discover ethereum zksync2 --dev
node -r esbuild-register ../discovery/src/cli.ts discover ethereum zora --dev
node -r esbuild-register ../discovery/src/cli.ts discover zksync2 abstract --dev
node -r esbuild-register ../discovery/src/cli.ts discover zksync2 cronoszkevm --dev
node -r esbuild-register ../discovery/src/cli.ts discover zksync2 grvt --dev
node -r esbuild-register ../discovery/src/cli.ts discover zksync2 shared-zk-stack --dev
node -r esbuild-register ../discovery/src/cli.ts discover zksync2 sophon --dev
node -r esbuild-register ../discovery/src/cli.ts discover zksync2 treasure --dev
node -r esbuild-register ../discovery/src/cli.ts discover zksync2 zeronetwork --dev
node -r esbuild-register ../discovery/src/cli.ts discover zksync2 zklinknova --dev
node -r esbuild-register ../discovery/src/cli.ts discover zksync2 zksync2 --dev
node -r esbuild-register ../discovery/src/cli.ts discover arbitrum apechain --dev
node -r esbuild-register ../discovery/src/cli.ts discover arbitrum arbitrum --dev
node -r esbuild-register ../discovery/src/cli.ts discover arbitrum blessnet --dev
node -r esbuild-register ../discovery/src/cli.ts discover arbitrum blobstream --dev
node -r esbuild-register ../discovery/src/cli.ts discover arbitrum deri --dev
node -r esbuild-register ../discovery/src/cli.ts discover arbitrum educhain --dev
node -r esbuild-register ../discovery/src/cli.ts discover arbitrum game7 --dev
node -r esbuild-register ../discovery/src/cli.ts discover arbitrum hyperliquid --dev
node -r esbuild-register ../discovery/src/cli.ts discover arbitrum inevm --dev
node -r esbuild-register ../discovery/src/cli.ts discover arbitrum l3x --dev
node -r esbuild-register ../discovery/src/cli.ts discover arbitrum lzomnichain --dev
node -r esbuild-register ../discovery/src/cli.ts discover arbitrum molten --dev
node -r esbuild-register ../discovery/src/cli.ts discover arbitrum muster --dev
node -r esbuild-register ../discovery/src/cli.ts discover arbitrum popapex --dev
node -r esbuild-register ../discovery/src/cli.ts discover arbitrum popboss --dev
node -r esbuild-register ../discovery/src/cli.ts discover arbitrum rari --dev
node -r esbuild-register ../discovery/src/cli.ts discover arbitrum sanko --dev
node -r esbuild-register ../discovery/src/cli.ts discover arbitrum stargatev2 --dev
node -r esbuild-register ../discovery/src/cli.ts discover arbitrum winr --dev
node -r esbuild-register ../discovery/src/cli.ts discover arbitrum xai --dev
node -r esbuild-register ../discovery/src/cli.ts discover arbitrum zklinknova --dev
node -r esbuild-register ../discovery/src/cli.ts discover base b3 --dev
node -r esbuild-register ../discovery/src/cli.ts discover base blobstream --dev
node -r esbuild-register ../discovery/src/cli.ts discover base degen --dev
node -r esbuild-register ../discovery/src/cli.ts discover base donatuz --dev
node -r esbuild-register ../discovery/src/cli.ts discover base geist --dev
node -r esbuild-register ../discovery/src/cli.ts discover base ham --dev
node -r esbuild-register ../discovery/src/cli.ts discover base lzomnichain --dev
node -r esbuild-register ../discovery/src/cli.ts discover base stack --dev
node -r esbuild-register ../discovery/src/cli.ts discover base stargatev2 --dev
node -r esbuild-register ../discovery/src/cli.ts discover base syndicateframe --dev
node -r esbuild-register ../discovery/src/cli.ts discover base zklinknova --dev
node -r esbuild-register ../discovery/src/cli.ts discover optimism bugbuster --dev
node -r esbuild-register ../discovery/src/cli.ts discover optimism lzomnichain --dev
node -r esbuild-register ../discovery/src/cli.ts discover optimism optimism --dev
node -r esbuild-register ../discovery/src/cli.ts discover optimism stargatev2 --dev
node -r esbuild-register ../discovery/src/cli.ts discover optimism worldcoin --dev
node -r esbuild-register ../discovery/src/cli.ts discover optimism zklinknova --dev
node -r esbuild-register ../discovery/src/cli.ts discover sepolia eip7702 --dev
node -r esbuild-register ../discovery/src/cli.ts discover ink ink --dev
node -r esbuild-register ../discovery/src/cli.ts discover kinto kinto --dev
node -r esbuild-register ../discovery/src/cli.ts discover bsc lzomnichain --dev
node -r esbuild-register ../discovery/src/cli.ts discover linea lzomnichain --dev
node -r esbuild-register ../discovery/src/cli.ts discover linea stargatev2 --dev
node -r esbuild-register ../discovery/src/cli.ts discover linea zklinknova --dev
node -r esbuild-register ../discovery/src/cli.ts discover polygonpos lzomnichain --dev
node -r esbuild-register ../discovery/src/cli.ts discover polygonzkevm lzomnichain --dev
node -r esbuild-register ../discovery/src/cli.ts discover nova nova --dev
node -r esbuild-register ../discovery/src/cli.ts discover nova playblock --dev
node -r esbuild-register ../discovery/src/cli.ts discover celo opticsV2 --dev
node -r esbuild-register ../discovery/src/cli.ts discover mantle stargatev2 --dev
node -r esbuild-register ../discovery/src/cli.ts discover mantle zklinknova --dev
node -r esbuild-register ../discovery/src/cli.ts discover metis stargatev2 --dev
node -r esbuild-register ../discovery/src/cli.ts discover scroll stargatev2 --dev
node -r esbuild-register ../discovery/src/cli.ts discover scroll zklinknova --dev
node -r esbuild-register ../discovery/src/cli.ts discover unichain unichain --dev
node -r esbuild-register ../discovery/src/cli.ts discover blast zklinknova --dev
node -r esbuild-register ../discovery/src/cli.ts discover mantapacific zklinknova --dev
