rm -rf src/projects/\(tokens\)/buidl/arbitrum
rm -rf src/projects/\(tokens\)/eurs/ethereum
rm -rf src/projects/\(tokens\)/ez-eth/ethereum
rm -rf src/projects/\(tokens\)/mog/base
rm -rf src/projects/\(tokens\)/mog/ethereum
rm -rf src/projects/\(tokens\)/pz-eth/ethereum
rm -rf src/projects/\(tokens\)/rs-eth/base
rm -rf src/projects/\(tokens\)/st-azur/ethereum
rm -rf src/projects/\(tokens\)/tradable/zksync2
rm -rf src/projects/\(tokens\)/usds/ethereum
rm -rf src/projects/\(tokens\)/usdy/arbitrum
rm -rf src/projects/\(tokens\)/w/arbitrum
rm -rf src/projects/\(tokens\)/w/base
rm -rf src/projects/\(tokens\)/yieldfi/ethereum
rm -rf src/projects/abstract/ethereum
rm -rf src/projects/abstract/zksync2
rm -rf src/projects/across-v3/ethereum
rm -rf src/projects/aevo/ethereum
rm -rf src/projects/alephzero/ethereum
rm -rf src/projects/alienx/ethereum
rm -rf src/projects/allbridge/ethereum
rm -rf src/projects/amarok/ethereum
rm -rf src/projects/ancient/ethereum
rm -rf src/projects/apechain/arbitrum
rm -rf src/projects/apex/ethereum
rm -rf src/projects/appchain/ethereum
rm -rf src/projects/aptos/ethereum
rm -rf src/projects/arbitrum/arbitrum
rm -rf src/projects/arbitrum/ethereum
rm -rf src/projects/arenaz/ethereum
rm -rf src/projects/astarzkevm/ethereum
rm -rf src/projects/automata/ethereum
rm -rf src/projects/avalanche/ethereum
rm -rf src/projects/aztec/ethereum
rm -rf src/projects/aztecconnect/ethereum
rm -rf src/projects/b3/base
rm -rf src/projects/base/base
rm -rf src/projects/base/ethereum
rm -rf src/projects/beamer-bridge-v2/ethereum
rm -rf src/projects/blast/ethereum
rm -rf src/projects/blessnet/arbitrum
rm -rf src/projects/blobstream/arbitrum
rm -rf src/projects/blobstream/base
rm -rf src/projects/blobstream/ethereum
rm -rf src/projects/bob/ethereum
rm -rf src/projects/bobanetwork/ethereum
rm -rf src/projects/brine/ethereum
rm -rf src/projects/bugbuster/optimism
rm -rf src/projects/canvasconnect/ethereum
rm -rf src/projects/cartesi-prt-honeypot/ethereum
rm -rf src/projects/cbridge/ethereum
rm -rf src/projects/celo/ethereum
rm -rf src/projects/chainport/ethereum
rm -rf src/projects/connext/ethereum
rm -rf src/projects/corn/ethereum
rm -rf src/projects/cronoszkevm/ethereum
rm -rf src/projects/cronoszkevm/zksync2
rm -rf src/projects/cyber/ethereum
rm -rf src/projects/dbk/ethereum
rm -rf src/projects/debridge/ethereum
rm -rf src/projects/degate/ethereum
rm -rf src/projects/degate2/ethereum
rm -rf src/projects/degate3/ethereum
rm -rf src/projects/degen/base
rm -rf src/projects/deri/arbitrum
rm -rf src/projects/deversifi/ethereum
rm -rf src/projects/donatuz/base
rm -rf src/projects/dydx/ethereum
rm -rf src/projects/ebichain/ethereum
rm -rf src/projects/eclipse/ethereum
rm -rf src/projects/edgeless/ethereum
rm -rf src/projects/educhain/arbitrum
rm -rf src/projects/eigenda/ethereum
rm -rf src/projects/espresso/ethereum
rm -rf src/projects/ethernity/ethereum
rm -rf src/projects/everclear/ethereum
rm -rf src/projects/everclearbridge/ethereum
rm -rf src/projects/everclearbridge/everclear
rm -rf src/projects/facet/ethereum
rm -rf src/projects/facet/facet
rm -rf src/projects/fluence/ethereum
rm -rf src/projects/form/ethereum
rm -rf src/projects/fraxferry/ethereum
rm -rf src/projects/fraxtal/ethereum
rm -rf src/projects/fuel/ethereum
rm -rf src/projects/fuelv1/ethereum
rm -rf src/projects/funki/ethereum
rm -rf src/projects/galxegravity/ethereum
rm -rf src/projects/game7/arbitrum
rm -rf src/projects/gateway/ethereum
rm -rf src/projects/gateway/gateway
rm -rf src/projects/geist/base
rm -rf src/projects/gluon/ethereum
rm -rf src/projects/gmnetwork/ethereum
rm -rf src/projects/gpt/ethereum
rm -rf src/projects/gravity/ethereum
rm -rf src/projects/grvt/ethereum
rm -rf src/projects/grvt/zksync2
rm -rf src/projects/ham/base
rm -rf src/projects/hashkey/ethereum
rm -rf src/projects/hemi/ethereum
rm -rf src/projects/hermez/ethereum
rm -rf src/projects/hibachi/arbitrum
rm -rf src/projects/honeypot/ethereum
rm -rf src/projects/hop/ethereum
rm -rf src/projects/hychain/ethereum
rm -rf src/projects/hyperlane/ethereum
rm -rf src/projects/hyperliquid/arbitrum
rm -rf src/projects/hyphen/ethereum
rm -rf src/projects/hypr/ethereum
rm -rf src/projects/immutablex/ethereum
rm -rf src/projects/immutablezkevm/ethereum
rm -rf src/projects/inevm/arbitrum
rm -rf src/projects/ink/ethereum
rm -rf src/projects/ink/ink
rm -rf src/projects/intmax/ethereum
rm -rf src/projects/intmax/scroll
rm -rf src/projects/karak/ethereum
rm -rf src/projects/katana/ethereum
rm -rf src/projects/kinto/ethereum
rm -rf src/projects/kinto/kinto
rm -rf src/projects/kroma/ethereum
rm -rf src/projects/l3x/arbitrum
rm -rf src/projects/lachain/ethereum
rm -rf src/projects/lachain/zksync2
rm -rf src/projects/lambda/ethereum
rm -rf src/projects/lasernet/ethereum
rm -rf src/projects/layer2finance/ethereum
rm -rf src/projects/layer2financezk/ethereum
rm -rf src/projects/layerzerov2oft/ethereum
rm -rf src/projects/lens/ethereum
rm -rf src/projects/lens/zksync2
rm -rf src/projects/lightlink/ethereum
rm -rf src/projects/linea/ethereum
rm -rf src/projects/linea/linea
rm -rf src/projects/lisk/ethereum
rm -rf src/projects/loopring/ethereum
rm -rf src/projects/lumia/ethereum
rm -rf src/projects/lyra/ethereum
rm -rf src/projects/lzomnichain/ethereum
rm -rf src/projects/mantapacific/ethereum
rm -rf src/projects/mantle/ethereum
rm -rf src/projects/metal/ethereum
rm -rf src/projects/metis/ethereum
rm -rf src/projects/mint/ethereum
rm -rf src/projects/mode/ethereum
rm -rf src/projects/molten/arbitrum
rm -rf src/projects/morph/ethereum
rm -rf src/projects/multichain/ethereum
rm -rf src/projects/muster/arbitrum
rm -rf src/projects/myria/ethereum
rm -rf src/projects/near/ethereum
rm -rf src/projects/nearomni/ethereum
rm -rf src/projects/nebraupa/ethereum
rm -rf src/projects/nomad/ethereum
rm -rf src/projects/nova/ethereum
rm -rf src/projects/nova/nova
rm -rf src/projects/oevnetwork/ethereum
rm -rf src/projects/omgnetwork/ethereum
rm -rf src/projects/omni/ethereum
rm -rf src/projects/omni/gnosis
rm -rf src/projects/opticsV1/ethereum
rm -rf src/projects/opticsV2/ethereum
rm -rf src/projects/optimism/ethereum
rm -rf src/projects/optimism/optimism
rm -rf src/projects/optopia/ethereum
rm -rf src/projects/orbit/ethereum
rm -rf src/projects/orbiter/ethereum
rm -rf src/projects/orderly/ethereum
rm -rf src/projects/paradex/ethereum
rm -rf src/projects/parallel/ethereum
rm -rf src/projects/penchain/ethereum
rm -rf src/projects/pepeunchained/ethereum
rm -rf src/projects/pepeunchained2/ethereum
rm -rf src/projects/phala/ethereum
rm -rf src/projects/playblock/nova
rm -rf src/projects/plumenetwork/ethereum
rm -rf src/projects/pNetwork/ethereum
rm -rf src/projects/polygon-pos/ethereum
rm -rf src/projects/polygonzkevm/ethereum
rm -rf src/projects/polynetwork/ethereum
rm -rf src/projects/polynomial/ethereum
rm -rf src/projects/popapex/arbitrum
rm -rf src/projects/popboss/arbitrum
rm -rf src/projects/portal/ethereum
rm -rf src/projects/publicgoodsnetwork/ethereum
rm -rf src/projects/pulseChain/ethereum
rm -rf src/projects/r0ar/ethereum
rm -rf src/projects/race/ethereum
rm -rf src/projects/rari/arbitrum
rm -rf src/projects/real/ethereum
rm -rf src/projects/reddioex/ethereum
rm -rf src/projects/redstone/ethereum
rm -rf src/projects/reya/ethereum
rm -rf src/projects/river/ethereum
rm -rf src/projects/ronin/ethereum
rm -rf src/projects/rss3/ethereum
rm -rf src/projects/sanko/arbitrum
rm -rf src/projects/satellite/ethereum
rm -rf src/projects/scroll/ethereum
rm -rf src/projects/scroll/scroll
rm -rf src/projects/settlus/ethereum
rm -rf src/projects/shape/ethereum
rm -rf src/projects/shared-eigenlayer/ethereum
rm -rf src/projects/shared-polygon-cdk/ethereum
rm -rf src/projects/shared-sharp-verifier/ethereum
rm -rf src/projects/shared-sp1/arbitrum
rm -rf src/projects/shared-sp1/base
rm -rf src/projects/shared-sp1/ethereum
rm -rf src/projects/shared-sp1/optimism
rm -rf src/projects/shared-sp1/scroll
rm -rf src/projects/shared-zk-stack/ethereum
rm -rf src/projects/shared-zk-stack/gateway
rm -rf src/projects/shared-zk-stack/zksync2
rm -rf src/projects/shibarium/ethereum
rm -rf src/projects/silicon/ethereum
rm -rf src/projects/skale-ima/ethereum
rm -rf src/projects/snaxchain/ethereum
rm -rf src/projects/socket/ethereum
rm -rf src/projects/sollet/ethereum
rm -rf src/projects/soneium/ethereum
rm -rf src/projects/sonicgateway/ethereum
rm -rf src/projects/soon/ethereum
rm -rf src/projects/sophon/ethereum
rm -rf src/projects/sophon/zksync2
rm -rf src/projects/sorare/ethereum
rm -rf src/projects/stack/base
rm -rf src/projects/stargate/ethereum
rm -rf src/projects/stargatev2/arbitrum
rm -rf src/projects/stargatev2/base
rm -rf src/projects/stargatev2/ethereum
rm -rf src/projects/stargatev2/linea
rm -rf src/projects/stargatev2/optimism
rm -rf src/projects/stargatev2/scroll
rm -rf src/projects/starknet/ethereum
rm -rf src/projects/superlumio/ethereum
rm -rf src/projects/superposition/arbitrum
rm -rf src/projects/superseed/ethereum
rm -rf src/projects/swan/ethereum
rm -rf src/projects/swell/ethereum
rm -rf src/projects/sxnetwork/ethereum
rm -rf src/projects/sxt/ethereum
rm -rf src/projects/sxt/zksync2
rm -rf src/projects/sygma/ethereum
rm -rf src/projects/symbiosis/ethereum
rm -rf src/projects/synapse/ethereum
rm -rf src/projects/syndicateframe/base
rm -rf src/projects/taiko/ethereum
rm -rf src/projects/taiko/taiko
rm -rf src/projects/termstructure/ethereum
rm -rf src/projects/ternoa/ethereum
rm -rf src/projects/thebinaryholdings/ethereum
rm -rf src/projects/tokens/arbitrum
rm -rf src/projects/tokens/base
rm -rf src/projects/tokens/ethereum
rm -rf src/projects/transporter/ethereum
rm -rf src/projects/treasure/ethereum
rm -rf src/projects/treasure/zksync2
rm -rf src/projects/unichain/ethereum
rm -rf src/projects/unichain/unichain
rm -rf src/projects/vector/ethereum
rm -rf src/projects/winr/arbitrum
rm -rf src/projects/wirex/ethereum
rm -rf src/projects/witness/ethereum
rm -rf src/projects/wonder/ethereum
rm -rf src/projects/wonder/zksync2
rm -rf src/projects/worldchain/ethereum
rm -rf src/projects/worldcoin/ethereum
rm -rf src/projects/worldcoin/optimism
rm -rf src/projects/xai/arbitrum
rm -rf src/projects/xchain/ethereum
rm -rf src/projects/xlayer/ethereum
rm -rf src/projects/xterio/ethereum
rm -rf src/projects/zeronetwork/ethereum
rm -rf src/projects/zeronetwork/zksync2
rm -rf src/projects/zircuit/ethereum
rm -rf src/projects/zircuit/zircuit
rm -rf src/projects/zkcandy/ethereum
rm -rf src/projects/zkcandy/zksync2
rm -rf src/projects/zkfair/ethereum
rm -rf src/projects/zklinknova/arbitrum
rm -rf src/projects/zklinknova/base
rm -rf src/projects/zklinknova/blast
rm -rf src/projects/zklinknova/ethereum
rm -rf src/projects/zklinknova/linea
rm -rf src/projects/zklinknova/mantapacific
rm -rf src/projects/zklinknova/mantle
rm -rf src/projects/zklinknova/optimism
rm -rf src/projects/zklinknova/scroll
rm -rf src/projects/zklinknova/zksync2
rm -rf src/projects/zkspace/ethereum
rm -rf src/projects/zkswap/ethereum
rm -rf src/projects/zkswap2/ethereum
rm -rf src/projects/zksync/ethereum
rm -rf src/projects/zksync2/ethereum
rm -rf src/projects/zksync2/gateway
rm -rf src/projects/zksync2/zksync2
rm -rf src/projects/zora/ethereum
