import { Logger } from '@l2beat/backend-tools'
import { HttpClient, RetryHandler } from '@l2beat/shared'
import type { EthereumAddress } from '@l2beat/shared-pure'
import * as cheerio from 'cheerio'
import { writeFileSync } from 'fs'
import groupBy from 'lodash/groupBy'
import { ProjectService } from '../../src'

const SOURCE_FILE_PATH = './src/tokens/rwa.json'
const DB_PATH = './build/db.sqlite'

main().catch((e: unknown) => {
  console.error(e)
})

type RwaTokenInfo = {
  id: string
  symbol: string
  address: EthereumAddress | undefined
  categories: string[]
  isStablecoin: boolean | null
  isOnRWA: boolean
}

async function main() {
  const ps = new ProjectService(DB_PATH)
  const tokens = await ps.getTokens()
  let counter = 0

  const bySymbol = groupBy(tokens, 'symbol')
  const entries = Object.entries(bySymbol).sort(([symbolA], [symbolB]) =>
    symbolA.localeCompare(symbolB),
  )

  const output: RwaTokenInfo[] = []

  const tasks = entries.map(async ([symbol, tokensInGroup]) => {
    const html = await fetchRwaPage(`assets/${remapSymbol(symbol)}`)
    counter += tokensInGroup.length

    console.log(
      `${counter}/${tokens.length} (${tokensInGroup.length}) - ${symbol}`,
    )

    if (!html) {
      // We've got no response - asset not listed
      // we fill the output with null values
      for (const token of tokensInGroup) {
        output.push({
          id: token.id,
          symbol: token.symbol,
          address: token.address,
          categories: [],
          isStablecoin: null,
          isOnRWA: false,
        } satisfies RwaTokenInfo)
      }
      return
    }

    // We've got redirected to the main page - asset not listed
    // we fill the output with null values
    if (isMainPage(html)) {
      for (const token of tokensInGroup) {
        output.push({
          id: token.id,
          symbol: token.symbol,
          address: token.address,
          categories: [],
          isStablecoin: null,
          isOnRWA: false,
        } satisfies RwaTokenInfo)
      }
      return
    }

    const categories = extractCategories(html)

    for (const token of tokensInGroup) {
      output.push({
        id: token.id,
        symbol: token.symbol,
        address: token.address,
        categories,
        isStablecoin: categories.includes('Stablecoins'),
        isOnRWA: true,
      } satisfies RwaTokenInfo)
    }
  })

  for (const task of tasks) {
    await task
  }

  saveOutput(output)
}

async function fetchRwaPage(path: string) {
  const logger = Logger.INFO.for('RWA').configure({
    logLevel: 'NONE',
  })

  const strategy = new RetryHandler({
    maxRetries: 10,
    initialRetryDelayMs: 1000,
    maxRetryDelayMs: 100_000,
    logger,
  })
  const client = new HttpClient()

  const result = await strategy.retry(async () => {
    const res = await client.fetchRaw(`https://app.rwa.xyz/${path}`, {
      timeout: 100_000,
    })

    if (!res.ok) {
      throw new Error(`Error fetching RWA page for ${path}: ${res.status}`)
    }

    return res
  })

  return result.text()
}

function isMainPage(html: string) {
  const $ = cheerio.load(html)

  const title = $('title').text()

  return title === 'RWA.xyz | Analytics on Tokenized Real-World Assets'
}

function extractCategories(html: string): string[] {
  const $ = cheerio.load(html)

  const categoriesDiv = $(
    '#__next > div.flex.flex-1.flex-col.md\\:pl-\\[250px\\] > main > div > div > div.flex.flex-col.gap-4.mb-4 > div > div.flex.flex-col > div.flex.flex-wrap.items-center.gap-3',
  )

  return categoriesDiv
    .children('span')
    .map((_, el) => $(el).text())
    .get()
}

const remaps: Record<string, string> = {
  'USDC.e': 'USDC',
}

function remapSymbol(symbol: string): string {
  return symbol in remaps ? remaps[symbol] : symbol
}

function saveOutput(output: RwaTokenInfo[]) {
  const comment =
    'This file was autogenerated. Please do not edit it manually. Generated on ' +
    new Date().toISOString()

  writeFileSync(
    SOURCE_FILE_PATH,
    JSON.stringify(
      {
        comment,
        tokens: output.sort((a, b) => a.symbol.localeCompare(b.symbol)),
      },
      null,
      2,
    ),
  )
}
