export type ScalingProjectPurpose =
  | 'AI'
  | 'AMM'
  | 'Auctions'
  | 'Bitcoin DApps'
  | 'Bug bounty'
  | 'DeFi'
  | 'Exchange'
  | 'Gaming'
  | 'Information'
  | 'Launchpad'
  | 'NFT'
  | 'Payments'
  | 'Private payments'
  | 'Privacy'
  | 'Universal'
  | 'Social'
  | 'RWA'
  | 'IoT'
  | 'Restaking'
