export type ScalingProjectPurpose =
  | 'Bitcoin DApps'
  | 'Bug bounty'
  | 'DEX'
  | 'DeFi'
  | 'Exchange'
  | 'Gaming'
  | 'Launchpad'
  | 'NFT'
  | 'Payments'
  | 'AMM'
  | 'Privacy'
  | 'Finance'
  | 'Private DeFi'
  | 'Private payments'
  | 'Tokens'
  | 'Universal'
  | 'Encrypted'
  | 'Social'
