name: Deploy website

on:
  push:
    branches:
      - master
  # everyday at 2 am
  schedule:
    - cron: "0 2 * * *"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14.x
      - name: Backend cache.json
        id: cache
        uses: actions/cache@v2
        with:
          path: ./backend/cache/cache.json
          # Update the version if cache format changes
          key: cache-json-v-2-${{ github.run_id }}
          restore-keys: |
            cache-json-v-2-
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - name: Restore yarn cache
        uses: actions/cache@v2
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - run: yarn --frozen-lockfile
      - run: yarn build
        env:
          RPC_URL: ${{ secrets.BC_NODE }}
          ETHERSCAN_API_KEY: ${{ secrets.ETHERSCAN_API_KEY }}
      - name: Upload frontend
        run: yarn netlify deploy -d build --prod
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        working-directory: ./website
