name: Deploy website

on:
  push:
    branches:
      - master
  # every hour
  schedule:
    - cron: "0 * * * *"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - run: yarn --frozen-lockfile
      - run: yarn build:dependencies
      - run: cd packages/config && yarn check-verified-contracts
      - run: cd packages/frontend && yarn build
        env:
          RPC_URL: ${{ secrets.BC_NODE }}
          ETHERSCAN_API_KEY: ${{ secrets.ETHERSCAN_API_KEY }}
      - name: Upload frontend
        run: npx netlify-cli deploy -d packages/frontend/build --prod
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
