name: Deploy website

on:
  pull_request: # to remove
  schedule:
    - cron: "0 * * * *"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger rebuild on vercel
        run: curl -X POST ${{ secrets.VERCEL_REBUILD_MASTER_HOOK }}
