name: Deploy frontend 

concurrency:
  group: frontend-deployment
permissions:
  contents: read
  packages: write

on:
  pull_request:

jobs:
  build:
    uses: ./.github/workflows/build-docker-image.yml
    with:
      project: frontend
      dockerfile: packages/frontend/Dockerfile
    secrets:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ vars.TURBO_TEAM }}