name: Deploy website

on:
  push:
    branches:
      - master
      - netlify
  # everyday at 2 am
  schedule:
    - cron: "0 2 * * *"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14.x
      - name: Backend cache.json
        id: cache
        uses: actions/cache@v2
        with:
          path: ./backend/cache/cache.json
          # Update the version if cache format changes
          key: cache-json-v-1-${{ github.run_id }}
          restore-keys: |
            cache-json-v-1-
      - run: yarn --frozen-lockfile
      - name: Build shared config
        run: yarn build
        working-directory: config
      - name: Generate data.json
        run: yarn start
        env:
          RPC_URL: ${{ secrets.BC_NODE }}
          ETHERSCAN_API_KEY: ${{ secrets.ETHERSCAN_API_KEY }}
        working-directory: backend
      - name: Build frontend
        run: yarn build
        working-directory: frontend
      - name: Upload frontend 
        run: yarn netlify deploy --prod
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        working-directory: ./frontend
