name: Deploy update monitor on PoC environment

concurrency:
  group: do-poc
permissions: {}

on:
  schedule:
    - cron: "45 * * * *"

jobs:
  deploy-update-monitor:
    name: Deploy update monitor
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Login to DO container registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DO_POC_USER }}
          password: ${{ secrets.DO_POC_TOKEN }}
          registry: ${{ secrets.DO_POC_REGISTRY }}
      - name: Build and publish containers
        uses: docker/build-push-action@v5
        with:
          push: true
          file: Dockerfile.backend
          build-args: |
            TURBO_TEAM=${{ vars.TURBO_TEAM }}
            TURBO_TOKEN=${{ secrets.TURBO_TOKEN }}
          tags: |
            ${{ secrets.DO_POC_REGISTRY }}/l2beat/update-monitor
