name: Generate og images

on:
  push:
    branches:
      - master
jobs:
  generate:
    strategy:
      matrix:
        node: ["15.x"]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "15.x"

      - name: Cache YARN dependencies
        uses: actions/cache@v2
        with:
          path: |
            frontend/node_modules
            frontend/*/*/node_modules
          key: ${{ runner.OS }}-${{ matrix.node }}-yarn-cache-${{ hashFiles('**/yarn.lock') }}
          restore-keys: ${{ runner.OS }}-${{ matrix.node }}-yarn-cache-

      - run: yarn --no-progress --non-interactive --frozen-lockfile
        working-directory: ./frontend

      - run: ./node_modules/.bin/ts-node --project ./tsconfig.json ./scripts/generateOgImages.ts
        working-directory: ./frontend

      - name: Push changes
        run: |
          git config --global user.name 'Og Bot 🤖'
          git config --global user.email 'og-bot@noreply.github.com'
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{$GITHUB_REPOSITORY}}
          git checkout "${{GITHUB_SHA}}"
          git add -A
          git commit -m "Generate images"
          git push
