name: Rebuild site every hour

on:
  schedule:
    - cron: "0 * * * *"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger production rebuild on vercel
        run: curl -X POST ${{ secrets.VERCEL_REBUILD_MASTER_HOOK }}

      - name: Trigger staging rebuild on vercel
        run: curl -X POST ${{ secrets.VERCEL_REBUILD_STAGING_MASTER_HOOK }}
