name: Refresh data

on:
  # everyday at 2 am
  schedule:
    - cron: "0 2 * * *"

jobs:
  refresh:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: Cache
        id: cache
        uses: actions/cache@v2
        with:
          path: ./backend/cache/cache.json
          # Update the version if cache format changes
          key: cache-json-v-1-${{ github.run_id }}
          restore-keys: |
            cache-json-v-1-
      - run: yarn --frozen-lockfile
        working-directory: ./backend
      - name: Generate data.json
        run: yarn start
        env:
          RPC_URL: ${{ secrets.BC_NODE }}
          ETHERSCAN_API_KEY: ${{ secrets.ETHERSCAN_API_KEY }}
        working-directory: ./backend
      - name: Commit to master
        uses: ActionwareIO/branch-push-action@action
        with:
          branch: master
          files: |
            data/data.json
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
