name: Release (canary)

on:
  push:
    branches:
      - main
    paths:
      - 'packages/backend-tools/**'
      - 'packages/uif/**'
      - '.github/workflows/release-canary.yml'

jobs:
  release-canary:
    name: Release (canary)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: 'yarn'

      - run: yarn --frozen-lockfile
      - run: yarn build

      - name: Set backend-tools version
        run: |
          yarn changeset version
          cd packages/backend-tools
          npm pkg set version=$(cat package.json | jq .version -r)-canary.$(date +'%Y%m%dT%H%M%S')
          echo "Version changed: $(npm pkg get version)"

      - name: Set uif version
        run: |
          yarn changeset version
          cd packages/uif
          npm pkg set version=$(cat package.json | jq .version -r)-canary.$(date +'%Y%m%dT%H%M%S')
          echo "Version changed: $(npm pkg get version)"

      - name: Set discovery-types version
        run: |
          yarn changeset version
          cd packages/discovery-types
          npm pkg set version=$(cat package.json | jq .version -r)-canary.$(date +'%Y%m%dT%H%M%S')
          echo "Version changed: $(npm pkg get version)"

      - name: Set discovery version
        run: |
          yarn changeset version
          cd packages/discovery
          npm pkg set version=$(cat package.json | jq .version -r)-canary.$(date +'%Y%m%dT%H%M%S')
          echo "Version changed: $(npm pkg get version)"

      - name: Publish backend-tools to npm
        uses: JS-DevTools/npm-publish@v1
        with:
          package: packages/backend-tools/package.json
          token: ${{ secrets.NPM_TOKEN }}
          dry-run: false
          tag: canary
          access: public

      - name: Publish uif to npm
        uses: JS-DevTools/npm-publish@v1
        with:
          package: packages/uif/package.json
          token: ${{ secrets.NPM_TOKEN }}
          dry-run: false
          tag: canary
          access: public

      - name: Publish discovery-types to npm
        uses: JS-DevTools/npm-publish@v1
        with:
          package: packages/discovery-types/package.json
          token: ${{ secrets.NPM_TOKEN }}
          dry-run: false
          tag: canary
          access: public

      - name: Publish discovery to npm
        uses: JS-DevTools/npm-publish@v1
        with:
          package: packages/discovery/package.json
          token: ${{ secrets.NPM_TOKEN }}
          dry-run: false
          tag: canary
          access: public
