name: (TEST) Run cache warmer

on:
  pull_request:

jobs:
  cache-warmup:
    name: Run cache warmer
    runs-on: ubuntu-latest
    timeout-minutes: 10
    env:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ vars.TURBO_TEAM }}
      TURBO_REMOTE_CACHE_UPLOAD_TIMEOUT: 10
      HEROKU_ORGANIZATION: ${{ vars.HEROKU_ORG }}
      HEROKU_API_KEY: ${{ secrets.HEROKU_TOKEN }}
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'
  
          
      - name: Install dependencies
        run: pnpm install
        
      - name: Install Heroku CLI
        run: curl https://cli-assets.heroku.com/install.sh | sh
          
      - name: Pull frontend configuration
        run: heroku config -a l2beat-website-prod --shell > .env
        working-directory: packages/frontend
      
      - name: Fill PORT variable
        run: echo "PORT=3000" >> .env
        working-directory: packages/frontend

      - name: Build frontend dependencies
        run: pnpm build:frontend

      - name: Run hot cache
        run: pnpm hot-cache
        working-directory: packages/frontend
