name: FULL Update L2 data into JSON files

on:
  workflow_dispatch:
  schedule:
    # RUNS EVERY WEEK
    - cron: "0 3 * * 0"

jobs:
  updateL2Data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 18.x

      - name: Install dependencies
        run: yarn --frozen-lockfile

      - name: Build packages
        run: yarn build:dependencies

      # - name: Goto configs
      #   run: cd packages/config

      # - name: Install dependencies
      #   run: yarn

      - name: Fetch and save L2s data
        run: cd packages/config && yarn && yarn layer2-details

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          delete-branch: true
          author: Data parser bot <bot-12345@protonmail.com>
          commit-message: "chore[layer2]: Update data full"
          title: "chore[layer2]: Update data full"
          body: |
            - Update layer2 data
            Auto-generated by [create-pull-request][1]
            [1]: https://github.com/peter-evans/create-pull-request
          labels: automerge
          branch: update-layer2-parsed-data-full
