/**
 * Projects the ossification dataset release into the compact runtime input
 * used by the score (`OSSIFICATION_CURVE_AGE_KNOTS` in @l2beat/shared): one
 * knot per curve incident, its `codeAgeSeconds`.
 *
 * The only accepted input is the sibling checkout
 * ../ossification-dataset/dist/latest (incidents.json plus manifest.json),
 * release format version 2. There is intentionally
 * no fallback for older release formats.
 */
import { getDiscoveryPaths } from '@l2beat/discovery'
import { v } from '@l2beat/validate'
import { execFileSync } from 'child_process'
import { readFileSync, writeFileSync } from 'fs'
import path from 'path'

export function runCurve(check: boolean) {
  // packages/config/src/projects -> repo root -> sibling dataset checkout
  const repoRoot = path.resolve(getDiscoveryPaths().discovery, '../../../..')
  const datasetRoot = path.resolve(repoRoot, '../ossification-dataset')
  const outputPath = path.join(
    repoRoot,
    'packages/shared/src/ossification/ossificationCurve.ts',
  )

  const ageKnots = getCanonicalAgeKnots(
    JSON.parse(
      readFileSync(
        path.join(datasetRoot, 'dist/latest/incidents.json'),
        'utf8',
      ),
    ),
    JSON.parse(
      readFileSync(path.join(datasetRoot, 'dist/latest/manifest.json'), 'utf8'),
    ),
  )
  const head = execFileSync('git', ['-C', datasetRoot, 'rev-parse', 'HEAD'], {
    encoding: 'utf8',
  }).trim()
  // An uncommitted release must never masquerade as its parent commit —
  // scores change only at deliberate dataset releases.
  const dirty =
    execFileSync(
      'git',
      ['-C', datasetRoot, 'status', '--porcelain', '--', 'dist', 'schema'],
      { encoding: 'utf8' },
    ).trim().length > 0
  const revision = dirty ? `${head}-dirty` : head
  const output = renderOutput(ageKnots, revision)

  if (check) {
    if (readFileSync(outputPath, 'utf8') !== output) {
      throw new Error(
        `${outputPath} does not match the checked-out ossification dataset release`,
      )
    }
    console.log(
      `curve is current: ossification-dataset@${revision}, n=${ageKnots.length}`,
    )
    return
  }

  writeFileSync(outputPath, output)
  console.log(
    `wrote ${outputPath}\nossification-dataset@${revision}, n=${ageKnots.length}`,
  )
}

// The dataset owns cohort admission and full evidence validation. Pin the
// format we consume and validate only the runtime inputs here; reading the
// producer's current schema would also silently accept its future versions.
const NonNegativeInteger = v
  .number()
  .check(Number.isSafeInteger)
  .check((x) => x >= 0)
const Release = v.object({
  formatVersion: v.literal(2),
  incidents: v.array(v.object({ codeAgeSeconds: NonNegativeInteger })),
})
const Manifest = v.object({
  formatVersion: v.literal(2),
  counts: v.object({ curveIncidents: NonNegativeInteger }),
})

export function getCanonicalAgeKnots(
  releaseInput: unknown,
  manifestInput: unknown,
): number[] {
  const release = Release.parse(releaseInput)
  const manifest = Manifest.parse(manifestInput)
  const ageKnots = release.incidents.map((incident) => incident.codeAgeSeconds)
  if (ageKnots.length === 0) {
    throw new Error('Release must contain at least one curve incident')
  }
  if (ageKnots.some((age, i) => age < (ageKnots[i - 1] ?? 0))) {
    throw new Error('release.incidents must be sorted by codeAgeSeconds')
  }
  if (manifest.counts.curveIncidents !== ageKnots.length) {
    throw new Error('manifest.counts.curveIncidents does not match the release')
  }
  return ageKnots
}

function renderOutput(ageKnots: number[], revision: string): string {
  return `/**
 * GENERATED by \`l2b ossification curve\` — do not edit by hand.
 *
 * Source: ossification-dataset@${revision}
 * Canonical input: dist/latest/incidents.json, validated against
 * schema/release-incidents.schema.json by the dataset repository. One knot per
 * curve incident (its codeAgeSeconds); the remaining release fields are not
 * runtime inputs to the score.
 */
// biome-ignore format: preserve the canonical ageKnots serialization
export const OSSIFICATION_CURVE_AGE_KNOTS = ${JSON.stringify(ageKnots)} as const
`
}
